# frozen_string_literal: true

source 'http://rubygems.org'
ruby '3.4.10'

gem 'dotenv'
gem 'falcon'
gem 'graphql'
gem 'pg'
gem 'rack'
gem 'rackup'
gem 'rake'
gem 'sequel'
gem 'sorbet-runtime'

group :development do
  gem 'code-scanning-rubocop', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'sorbet'
end

group :development, :test do
  gem 'factory_bot'
  gem 'rspec'
  gem 'tapioca', require: false
end
