# frozen_string_literal: true

source 'http://rubygems.org'
ruby '3.4.10'

gem 'async-redis'
gem 'dotenv'
gem 'falcon'
gem 'graphql'
gem 'pg'
gem 'rack'
gem 'rackup'
gem 'rake'
gem 'redis'
gem 'resque'
gem 'roda'
gem 'sequel'
gem 'sequel-state-machine'
gem 'sorbet-runtime'
gem 'state_machines'

group :development do
  gem 'code-scanning-rubocop', require: false
  gem 'irb', require: false
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-sequel', require: false
  gem 'sorbet'
end

group :development, :test do
  gem 'csv'
  gem 'factory_bot'
  gem 'get_process_mem'
  gem 'memory_profiler'
  gem 'rack-test'
  gem 'rspec'
  gem 'tapioca', require: false
end
