# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AuditLog`.
# Please instead update this file by running `bin/tapioca dsl AuditLog`.


class AuditLog
  extend T::Generic
  include GeneratedAttributeMethods
  include GeneratedValidationMethods
  extend GeneratedClassMethods

  Elem = type_template { { fixed: ::AuditLog } }

  module GeneratedAttributeMethods
    sig { returns(T.nilable(String)) }
    def actor; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def actor=(value); end

    sig { returns(Time) }
    def at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def at=(value); end

    sig { returns(String) }
    def event; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def event=(value); end

    sig { returns(String) }
    def from_state; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def from_state=(value); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def id=(value); end

    sig { returns(T.nilable(String)) }
    def messages; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def messages=(value); end

    sig { returns(Integer) }
    def note_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def note_id=(value); end

    sig { returns(T.nilable(String)) }
    def reason; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def reason=(value); end

    sig { returns(String) }
    def to_state; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def to_state=(value); end
  end

  module GeneratedClassMethods
    sig { params(args: T.untyped).returns(T.nilable(::AuditLog)) }
    def [](*args); end

    sig { params(block: T.untyped).returns(T::Array[::AuditLog]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig do
      params(
        values: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(arg0: ::AuditLog).void)
      ).returns(::AuditLog)
    end
    def create(values = T.unsafe(nil), &block); end

    sig { returns(::AuditLog::PrivateDataset) }
    def dataset; end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::AuditLog)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog) }
    def first!(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::AuditLog)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def limit(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def select_append(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::AuditLog)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::AuditLog) }
    def with_pk!(pk); end
  end

  module GeneratedDatasetMethods
    sig { params(block: T.untyped).returns(T::Array[::AuditLog]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(block: T.proc.params(arg0: ::AuditLog).void).returns(::AuditLog::PrivateDataset) }
    def each(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::AuditLog)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog) }
    def first!(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::AuditLog).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def flat_map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::AuditLog)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def limit(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::AuditLog).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def select_append(*args, &block); end

    sig { returns(T.nilable(::AuditLog)) }
    def single_record; end

    sig { returns(T::Array[::AuditLog]) }
    def to_a; end

    sig { params(args: T.untyped, block: T.untyped).returns(::AuditLog::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::AuditLog)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::AuditLog) }
    def with_pk!(pk); end
  end

  module GeneratedValidationMethods
    sig do
      params(
        exact: Integer,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_exact_length(exact, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        with: Regexp,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_format(with, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        set: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_includes(set, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_integer(atts, opts = T.unsafe(nil)); end

    sig do
      params(
        range: Range,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_length_range(range, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        max: Integer,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_max_length(max, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        max: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_max_value(max, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        min: Integer,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_min_length(min, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        min: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_min_value(min, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_no_null_byte(atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_not_null(atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_numeric(atts, opts = T.unsafe(nil)); end

    sig do
      params(
        operator: Symbol,
        rhs: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_operator(operator, rhs, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_presence(atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_schema_types(atts = T.unsafe(nil), opts = T.unsafe(nil)); end

    sig do
      params(
        klass: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_type(klass, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.untyped).returns(T.untyped) }
    def validates_unique(*atts); end
  end

  class PrivateDataset < ::Sequel::Dataset
    extend T::Generic
    include GeneratedDatasetMethods

    Elem = type_member { { fixed: ::AuditLog } }
  end
end
