# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Note`.
# Please instead update this file by running `bin/tapioca dsl Note`.


class Note
  extend T::Generic
  include GeneratedAttributeMethods
  include GeneratedValidationMethods
  extend GeneratedStateMachineClassMethods
  include GeneratedStateMachineInstanceMethods
  extend GeneratedClassMethods
  include StateMachineInstanceHelperModule
  extend StateMachineClassHelperModule

  Elem = type_template { { fixed: ::Note } }

  module GeneratedAttributeMethods
    sig { returns(Time) }
    def created_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def created_at=(value); end

    sig { returns(T.nilable(Time)) }
    def due_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def due_at=(value); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def id=(value); end

    sig { returns(String) }
    def note; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def note=(value); end

    sig { returns(String) }
    def state; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def state=(value); end

    sig { returns(Time) }
    def updated_at; end

    sig { params(value: T.nilable(Time)).returns(T.nilable(Time)) }
    def updated_at=(value); end
  end

  module GeneratedClassMethods
    sig { params(args: T.untyped).returns(T.nilable(::Note)) }
    def [](*args); end

    sig { params(block: T.untyped).returns(T::Array[::Note]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig do
      params(
        values: T::Hash[Symbol, T.untyped],
        block: T.nilable(T.proc.params(arg0: ::Note).void)
      ).returns(::Note)
    end
    def create(values = T.unsafe(nil), &block); end

    sig { returns(::Note::PrivateDataset) }
    def dataset; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Note)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note) }
    def first!(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Note)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def limit(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def select_append(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Note)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Note) }
    def with_pk!(pk); end
  end

  module GeneratedDatasetMethods
    sig { params(block: T.untyped).returns(T::Array[::Note]) }
    def all(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(Integer) }
    def count(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def distinct(*args, &block); end

    sig { params(block: T.proc.params(arg0: ::Note).void).returns(::Note::PrivateDataset) }
    def each(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def eager(*args, &block); end

    sig { returns(T::Boolean) }
    def empty?; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def exclude(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def filter(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Note)) }
    def first(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note) }
    def first!(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Note).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def flat_map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def group(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def group_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def having(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(T.nilable(::Note)) }
    def last(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def limit(*args, &block); end

    sig do
      type_parameters(:U)
        .params(
          block: T.proc.params(arg0: ::Note).returns(T.type_parameter(:U))
        ).returns(T::Array[T.type_parameter(:U)])
    end
    def map(&block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def offset(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def order(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def order_by(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def reverse(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def select(*args, &block); end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def select_append(*args, &block); end

    sig { returns(T.nilable(::Note)) }
    def single_record; end

    sig { returns(T::Array[::Note]) }
    def to_a; end

    sig { params(args: T.untyped, block: T.untyped).returns(::Note::PrivateDataset) }
    def where(*args, &block); end

    sig { params(pk: T.untyped).returns(T.nilable(::Note)) }
    def with_pk(pk); end

    sig { params(pk: T.untyped).returns(::Note) }
    def with_pk!(pk); end
  end

  module GeneratedStateMachineClassMethods
    sig { params(event: T.any(String, T::Hash[Symbol, T.untyped]), accessor: Symbol).returns(T.untyped) }
    def timestamp_accessor(event, accessor); end

    sig do
      params(
        events_and_accessors: T::Array[[T.any(String, T::Hash[Symbol, T.untyped]), Symbol]]
      ).returns(T.untyped)
    end
    def timestamp_accessors(events_and_accessors); end
  end

  module GeneratedStateMachineInstanceMethods
    sig { params(event: Symbol, args: T.untyped).returns(::Note) }
    def must_process(event, *args); end

    sig { params(event: Symbol, args: T.untyped).returns(T::Boolean) }
    def process(event, *args); end
  end

  module GeneratedValidationMethods
    sig do
      params(
        exact: Integer,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_exact_length(exact, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        with: Regexp,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_format(with, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        set: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_includes(set, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_integer(atts, opts = T.unsafe(nil)); end

    sig do
      params(
        range: Range,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_length_range(range, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        max: Integer,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_max_length(max, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        max: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_max_value(max, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        min: Integer,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_min_length(min, atts, opts = T.unsafe(nil)); end

    sig do
      params(
        min: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_min_value(min, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_no_null_byte(atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_not_null(atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_numeric(atts, opts = T.unsafe(nil)); end

    sig do
      params(
        operator: Symbol,
        rhs: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_operator(operator, rhs, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_presence(atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.any(Symbol, T::Array[Symbol]), opts: T::Hash[Symbol, T.untyped]).returns(T.untyped) }
    def validates_schema_types(atts = T.unsafe(nil), opts = T.unsafe(nil)); end

    sig do
      params(
        klass: T.untyped,
        atts: T.any(Symbol, T::Array[Symbol]),
        opts: T::Hash[Symbol, T.untyped]
      ).returns(T.untyped)
    end
    def validates_type(klass, atts, opts = T.unsafe(nil)); end

    sig { params(atts: T.untyped).returns(T.untyped) }
    def validates_unique(*atts); end
  end

  class PrivateDataset < ::Sequel::Dataset
    extend T::Generic
    include GeneratedDatasetMethods

    Elem = type_member { { fixed: ::Note } }
  end

  module StateMachineClassHelperModule
    sig { params(event: T.any(String, Symbol)).returns(String) }
    def human_state_event_name(event); end

    sig { params(state: T.any(String, Symbol)).returns(String) }
    def human_state_name(state); end
  end

  module StateMachineInstanceHelperModule
    sig { params(args: T.untyped).returns(T::Boolean) }
    def archive(*args); end

    sig { params(args: T.untyped).returns(T::Boolean) }
    def archive!(*args); end

    sig { params(args: T.untyped).returns(T.nilable(::StateMachines::Transition)) }
    def archive_transition(*args); end

    sig { returns(T::Boolean) }
    def archived?; end

    sig { returns(T::Boolean) }
    def can_archive?; end

    sig { returns(T::Boolean) }
    def can_complete?; end

    sig { returns(T::Boolean) }
    def can_willnotdo?; end

    sig { params(args: T.untyped).returns(T::Boolean) }
    def complete(*args); end

    sig { params(args: T.untyped).returns(T::Boolean) }
    def complete!(*args); end

    sig { params(args: T.untyped).returns(T.nilable(::StateMachines::Transition)) }
    def complete_transition(*args); end

    sig { returns(T::Boolean) }
    def completed?; end

    sig { params(event: T.any(String, Symbol), args: T.untyped).returns(T::Boolean) }
    def fire_state_event(event, *args); end

    sig { returns(String) }
    def human_state_name; end

    sig { returns(T::Boolean) }
    def pending?; end

    sig { params(state: T.any(String, Symbol)).returns(T::Boolean) }
    def state?(state); end

    sig { params(args: T.untyped).returns(T::Array[T.any(String, Symbol)]) }
    def state_events(*args); end

    sig { returns(T.any(String, Symbol)) }
    def state_name; end

    sig { params(args: T.untyped).returns(T::Array[::StateMachines::Transition]) }
    def state_paths(*args); end

    sig { params(args: T.untyped).returns(T::Array[::StateMachines::Transition]) }
    def state_transitions(*args); end

    sig { params(args: T.untyped).returns(T::Boolean) }
    def willnotdo(*args); end

    sig { params(args: T.untyped).returns(T::Boolean) }
    def willnotdo!(*args); end

    sig { returns(T::Boolean) }
    def willnotdo?; end

    sig { params(args: T.untyped).returns(T.nilable(::StateMachines::Transition)) }
    def willnotdo_transition(*args); end
  end
end
