# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Inputs::NoteAttributesInput`.
# Please instead update this file by running `bin/tapioca dsl Types::Inputs::NoteAttributesInput`.


class Types::Inputs::NoteAttributesInput
  include GeneratedArgumentMethods

  sig { returns(T.nilable(::Time)) }
  def due_at; end

  sig { returns(T.nilable(::String)) }
  def note; end

  module GeneratedArgumentMethods
    sig { returns(T.nilable(Time)) }
    def due_at; end

    sig { returns(T.nilable(String)) }
    def note; end
  end
end
