# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-redis` gem.
# Please instead update this file by running `bin/tapioca gem async-redis`.


# @namespace
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2025, by Samuel Williams.
# Copyright, 2026, by Travis Bell.
# Released under the MIT License.
# Copyright, 2018-2025, by Samuel Williams.
#
# pkg:gem/async-redis#lib/async/redis/version.rb:6
module Async; end

# @namespace
#
# pkg:gem/async-redis#lib/async/redis/version.rb:7
module Async::Redis
  class << self
    # Create a local Redis endpoint.
    # @parameter options [Hash] Options for the endpoint.
    # @returns [Endpoint] A local Redis endpoint.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:21
    def local_endpoint(**options); end
  end
end

# A Redis client that provides connection pooling and context management.
#
# pkg:gem/async-redis#lib/async/redis/client.rb:27
class Async::Redis::Client
  include ::Protocol::Redis::Methods
  include ::Protocol::Redis::Methods::Generic
  include ::Protocol::Redis::Methods::Connection
  include ::Protocol::Redis::Methods::Server
  include ::Protocol::Redis::Methods::Cluster
  include ::Protocol::Redis::Methods::Geospatial
  include ::Protocol::Redis::Methods::Counting
  include ::Protocol::Redis::Methods::Hashes
  include ::Protocol::Redis::Methods::Lists
  include ::Protocol::Redis::Methods::Scripting
  include ::Protocol::Redis::Methods::Sets
  include ::Protocol::Redis::Methods::SortedSets
  include ::Protocol::Redis::Methods::Strings
  include ::Protocol::Redis::Methods::Streams
  include ::Protocol::Redis::Methods::Pubsub
  include ::Async::Redis::Client::Methods

  # Create a new Redis client.
  # @parameter endpoint [Endpoint] The Redis endpoint to connect to.
  # @parameter protocol [Protocol] The protocol to use for communication.
  # @parameter options [Hash] Additional options for the connection pool.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:152
  def initialize(endpoint = T.unsafe(nil), protocol: T.unsafe(nil), **options); end

  # @attribute [Endpoint] The Redis endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:160
  def endpoint; end

  # @attribute [Protocol] The communication protocol.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:163
  def protocol; end

  protected

  # pkg:gem/async-redis#lib/async/redis/client.rb:187
  def assign_default_tags(tags); end

  # pkg:gem/async-redis#lib/async/redis/client.rb:192
  def make_pool(**options); end

  class << self
    # Open a Redis client and optionally yield it in an async task.
    # @yields {|client, task| ...} If a block is given, yield the client in an async task.
    # 	@parameter client [Client] The Redis client instance.
    # 	@parameter task [Async::Task] The async task.
    # @returns [Client] The client if no block provided.
    # @returns [Object] The result of the block if block given.
    #
    # pkg:gem/async-redis#lib/async/redis/client.rb:171
    def open(*arguments, **options, &block); end
  end
end

# Methods module providing Redis-specific functionality.
#
# pkg:gem/async-redis#lib/async/redis/client.rb:31
module Async::Redis::Client::Methods
  # Execute a Redis command directly.
  # @parameter arguments [Array] The command and its arguments.
  # @returns [Object] The response from the Redis server.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:130
  def call(*arguments); end

  # Close the client and all its connections.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:141
  def close; end

  # pkg:gem/async-redis#lib/async/redis/client.rb:105
  def multi(&block); end

  # Deprecated.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:125
  def nested(&block); end

  # Execute commands in a pipeline for improved performance.
  # @yields {|context| ...} If a block is given, it will be executed within the pipeline context.
  # 	@parameter context [Context::Pipeline] The pipeline context.
  # @returns [Object] The result of the block if block given.
  # @returns [Context::Pipeline] The pipeline context if no block given.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:112
  def pipeline(&block); end

  # Subscribe to one or more channel patterns for pub/sub messaging.
  # @parameter patterns [Array(String)] The channel patterns to subscribe to.
  # @yields {|context| ...} If a block is given, it will be executed within the subscription context.
  # 	@parameter context [Context::Subscription] The subscription context.
  # @returns [Object] The result of the block if block given.
  # @returns [Context::Subscription] The subscription context if no block given.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:56
  def psubscribe(*patterns); end

  # Subscribe to one or more sharded channels for pub/sub messaging (Redis 7.0+).
  # @parameter channels [Array(String)] The sharded channels to subscribe to.
  # @yields {|context| ...} If a block is given, it will be executed within the subscription context.
  # 	@parameter context [Context::Subscription] The subscription context.
  # @returns [Object] The result of the block if block given.
  # @returns [Context::Subscription] The subscription context if no block given.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:75
  def ssubscribe(*channels); end

  # Subscribe to one or more channels for pub/sub messaging.
  # @parameter channels [Array(String)] The channels to subscribe to.
  # @yields {|context| ...} If a block is given, it will be executed within the subscription context.
  # 	@parameter context [Context::Subscription] The subscription context.
  # @returns [Object] The result of the block if block given.
  # @returns [Context::Subscription] The subscription context if no block given.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:38
  def subscribe(*channels); end

  # Execute commands within a Redis transaction.
  # @yields {|context| ...} If a block is given, it will be executed within the transaction context.
  # 	@parameter context [Context::Transaction] The transaction context.
  # @returns [Object] The result of the block if block given.
  # @returns [Context::Transaction] Else if no block is given, returns the transaction context.
  #
  # pkg:gem/async-redis#lib/async/redis/client.rb:93
  def transaction(&block); end
end

# A Redis cluster client that manages multiple Redis instances and handles cluster operations.
#
# pkg:gem/async-redis#lib/async/redis/cluster_client.rb:17
class Async::Redis::ClusterClient
  include ::Protocol::Redis::Cluster::Methods
  include ::Protocol::Redis::Cluster::Methods::Generic
  include ::Protocol::Redis::Cluster::Methods::Pubsub
  include ::Protocol::Redis::Cluster::Methods::Streams
  include ::Protocol::Redis::Cluster::Methods::Strings

  # Create a new instance of the cluster client.
  #
  # @property endpoints [Array(Endpoint)] The list of cluster endpoints.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:33
  def initialize(endpoints, **options); end

  # Get any available client from the cluster.
  # This is useful for operations that don't require slot-specific routing, such as global pub/sub operations, INFO commands, or other cluster-wide operations.
  # @parameter role [Symbol] The role of node to get (:master or :slave).
  # @returns [Client] A Redis client for any available node.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:92
  def any_client(role = T.unsafe(nil)); end

  # Get a client for a specific slot.
  # @parameter slot [Integer] The cluster slot number.
  # @parameter role [Symbol] The role of node to get (:master or :slave).
  # @returns [Client] The Redis client for the slot.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:72
  def client_for(slot, role = T.unsafe(nil)); end

  # Execute a block with clients for the given keys, grouped by cluster slot.
  # @parameter keys [Array] The keys to find clients for.
  # @parameter role [Symbol] The role of nodes to use (:master or :slave).
  # @parameter attempts [Integer] Number of retry attempts for cluster errors.
  # @yields {|client, keys| ...} Block called for each client-keys pair.
  # 	@parameter client [Client] The Redis client for the slot.
  # 	@parameter keys [Array] The keys handled by this client.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:46
  def clients_for(*keys, role: T.unsafe(nil), attempts: T.unsafe(nil)); end

  # Return Redis::Client for a given key.
  # Modified from https://github.com/antirez/redis-rb-cluster/blob/master/cluster.rb#L104-L117
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:201
  def slot_for(key); end

  # Calculate the hash slots for multiple keys.
  # @parameter keys [Array] The keys to calculate slots for.
  # @returns [Hash] A hash mapping slot numbers to arrays of keys.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:216
  def slots_for(keys); end

  # Subscribe to one or more sharded channels for pub/sub messaging in cluster environment.
  # The subscription will be created on the appropriate nodes responsible for each channel's hash slot.
  #
  # @parameter channels [Array(String)] The sharded channels to subscribe to.
  # @yields {|context| ...} If a block is given, it will be executed within the subscription context.
  # 	@parameter context [ClusterSubscription] The cluster subscription context.
  # @returns [Object] The result of the block if block given.
  # @returns [ClusterSubscription] The cluster subscription context if no block given.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:234
  def subscribe(*channels); end

  protected

  # This is the CRC16 algorithm used by Redis Cluster to hash keys.
  # Copied from https://github.com/antirez/redis-rb-cluster/blob/master/crc16.rb
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:185
  def crc16(bytes); end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:112
  def reload_cluster!(endpoints = T.unsafe(nil)); end
end

# pkg:gem/async-redis#lib/async/redis/cluster_client.rb:197
Async::Redis::ClusterClient::HASH_SLOTS = T.let(T.unsafe(nil), Integer)

# pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
class Async::Redis::ClusterClient::Node < ::Struct
  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def client; end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def client=(_); end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def endpoint; end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def endpoint=(_); end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def health; end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def health=(_); end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def id; end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def id=(_); end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def role; end

  # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
  def role=(_); end

  class << self
    # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
    def [](*_arg0); end

    # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
    def inspect; end

    # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
    def keyword_init?; end

    # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
    def members; end

    # pkg:gem/async-redis#lib/async/redis/cluster_client.rb:28
    def new(*_arg0); end
  end
end

# Raised when cluster configuration cannot be reloaded.
#
# pkg:gem/async-redis#lib/async/redis/cluster_client.rb:21
class Async::Redis::ClusterClient::ReloadError < ::StandardError; end

# Raised when no nodes are found for a specific slot.
#
# pkg:gem/async-redis#lib/async/redis/cluster_client.rb:25
class Async::Redis::ClusterClient::SlotError < ::StandardError; end

# pkg:gem/async-redis#lib/async/redis/cluster_client.rb:148
Async::Redis::ClusterClient::XMODEM_CRC16_LOOKUP = T.let(T.unsafe(nil), Array)

# Context for managing sharded subscriptions across multiple Redis cluster nodes.
# This class handles the complexity of subscribing to channels that may be distributed
# across different shards in a Redis cluster.
#
# pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:14
class Async::Redis::ClusterSubscription
  # Initialize a new shard subscription context.
  # @parameter cluster_client [ClusterClient] The cluster client to use.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:21
  def initialize(cluster_client, queue: T.unsafe(nil)); end

  # Get the list of currently subscribed channels.
  # @returns [Array(String)] The list of subscribed channels.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:118
  def channels; end

  # Close all shard subscriptions.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:31
  def close; end

  # Iterate over all messages from all subscribed shards.
  # @yields {|response| ...} Block called for each message.
  # 	@parameter response [Array] The message response.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:53
  def each; end

  # Listen for the next message from any subscribed shard.
  # @returns [Array] The next message response.
  # @raises [SubscriptionError] If the subscription has failed for any reason.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:44
  def listen; end

  # Get the number of active shard subscriptions.
  # @returns [Integer] The number of shard connections.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:124
  def shard_count; end

  # Subscribe to additional sharded channels.
  # @parameter channels [Array(String)] The channels to subscribe to.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:63
  def subscribe(channels); end

  # Unsubscribe from sharded channels.
  # @parameter channels [Array(String)] The channels to unsubscribe from.
  #
  # pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:94
  def unsubscribe(channels); end
end

# Represents a failure in the subscription process, e.g. network issues, shard failures.
#
# pkg:gem/async-redis#lib/async/redis/cluster_subscription.rb:16
class Async::Redis::ClusterSubscription::SubscriptionError < ::StandardError; end

# @namespace
#
# pkg:gem/async-redis#lib/async/redis/context/generic.rb:12
module Async::Redis::Context; end

# Base class for Redis command execution contexts.
#
# pkg:gem/async-redis#lib/async/redis/context/generic.rb:14
class Async::Redis::Context::Generic
  # Initialize a new generic context.
  # @parameter pool [Pool] The connection pool to use.
  # @parameter arguments [Array] Additional arguments for the context.
  #
  # pkg:gem/async-redis#lib/async/redis/context/generic.rb:18
  def initialize(pool, *arguments); end

  # Execute a Redis command and return the response.
  # @parameter command [String] The Redis command.
  # @parameter arguments [Array] The command arguments.
  # @returns [Object] The Redis response.
  #
  # pkg:gem/async-redis#lib/async/redis/context/generic.rb:55
  def call(command, *arguments); end

  # Close the context and release the connection back to the pool.
  #
  # pkg:gem/async-redis#lib/async/redis/context/generic.rb:24
  def close; end

  # @returns [Boolean] Whether the context is closed.
  #
  # pkg:gem/async-redis#lib/async/redis/context/generic.rb:32
  def closed?; end

  # Read a response from the Redis connection.
  # @returns [Object] The Redis response.
  #
  # pkg:gem/async-redis#lib/async/redis/context/generic.rb:45
  def read_response; end

  # Write a Redis command request to the connection.
  # @parameter command [String] The Redis command.
  # @parameter arguments [Array] The command arguments.
  #
  # pkg:gem/async-redis#lib/async/redis/context/generic.rb:39
  def write_request(command, *arguments); end
end

# Send multiple commands without waiting for the response, instead of sending them one by one.
#
# pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:14
class Async::Redis::Context::Pipeline < ::Async::Redis::Context::Generic
  include ::Protocol::Redis::Methods
  include ::Protocol::Redis::Methods::Generic
  include ::Protocol::Redis::Methods::Connection
  include ::Protocol::Redis::Methods::Server
  include ::Protocol::Redis::Methods::Cluster
  include ::Protocol::Redis::Methods::Geospatial
  include ::Protocol::Redis::Methods::Counting
  include ::Protocol::Redis::Methods::Hashes
  include ::Protocol::Redis::Methods::Lists
  include ::Protocol::Redis::Methods::Scripting
  include ::Protocol::Redis::Methods::Sets
  include ::Protocol::Redis::Methods::SortedSets
  include ::Protocol::Redis::Methods::Strings
  include ::Protocol::Redis::Methods::Streams
  include ::Protocol::Redis::Methods::Pubsub

  # Initialize a new pipeline context.
  # @parameter pool [Pool] The connection pool to use.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:39
  def initialize(pool); end

  # This method just accumulates the commands and their params.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:80
  def call(command, *arguments); end

  # Close the pipeline and flush all pending responses.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:98
  def close; end

  # Collect all pending responses.
  # @yields {...} Optional block to execute while collecting responses.
  # @returns [Array] Array of all responses if no block given.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:57
  def collect; end

  # Flush responses.
  # @parameter count [Integer] leave this many responses.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:48
  def flush(count = T.unsafe(nil)); end

  # Read a response from the pipeline.
  # @returns [Object] The next response in the pipeline.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:88
  def read_response; end

  # Get a synchronous wrapper for this pipeline.
  # @returns [Sync] A synchronous wrapper that executes commands immediately.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:68
  def sync; end

  # This method just accumulates the commands and their params.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:73
  def write_request(*_arg0); end
end

# A synchronous wrapper for pipeline operations that executes one command at a time.
#
# pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:18
class Async::Redis::Context::Pipeline::Sync
  include ::Protocol::Redis::Methods
  include ::Protocol::Redis::Methods::Generic
  include ::Protocol::Redis::Methods::Connection
  include ::Protocol::Redis::Methods::Server
  include ::Protocol::Redis::Methods::Cluster
  include ::Protocol::Redis::Methods::Geospatial
  include ::Protocol::Redis::Methods::Counting
  include ::Protocol::Redis::Methods::Hashes
  include ::Protocol::Redis::Methods::Lists
  include ::Protocol::Redis::Methods::Scripting
  include ::Protocol::Redis::Methods::Sets
  include ::Protocol::Redis::Methods::SortedSets
  include ::Protocol::Redis::Methods::Strings
  include ::Protocol::Redis::Methods::Streams
  include ::Protocol::Redis::Methods::Pubsub

  # Initialize a new sync wrapper.
  # @parameter pipeline [Pipeline] The pipeline to wrap.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:23
  def initialize(pipeline); end

  # This method just accumulates the commands and their params.
  #
  # pkg:gem/async-redis#lib/async/redis/context/pipeline.rb:28
  def call(*_arg0, **_arg1, &_arg2); end
end

# Context for Redis pub/sub subscription operations.
#
# pkg:gem/async-redis#lib/async/redis/context/subscription.rb:13
class Async::Redis::Context::Subscription < ::Async::Redis::Context::Generic
  # Initialize a new subscription context.
  # @parameter pool [Pool] The connection pool to use.
  # @parameter channels [Array(String)] The channels to subscribe to.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:21
  def initialize(pool, channels); end

  # Close the subscription context.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:28
  def close; end

  # Iterate over all messages from subscribed channels.
  # @yields {|response| ...} Block called for each message.
  # 	@parameter response [Array] The message response.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:50
  def each; end

  # Listen for the next message from subscribed channels.
  # @returns [Array] The next message response, or nil if connection closed.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:37
  def listen; end

  # Subscribe to channel patterns.
  # @parameter patterns [Array(String)] The channel patterns to subscribe to.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:74
  def psubscribe(patterns); end

  # Unsubscribe from channel patterns.
  # @parameter patterns [Array(String)] The channel patterns to unsubscribe from.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:81
  def punsubscribe(patterns); end

  # Subscribe to sharded channels (Redis 7.0+).
  # @parameter channels [Array(String)] The sharded channels to subscribe to.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:88
  def ssubscribe(channels); end

  # Subscribe to additional channels.
  # @parameter channels [Array(String)] The channels to subscribe to.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:60
  def subscribe(channels); end

  # Unsubscribe from sharded channels (Redis 7.0+).
  # @parameter channels [Array(String)] The sharded channels to unsubscribe from.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:95
  def sunsubscribe(channels); end

  # Unsubscribe from channels.
  # @parameter channels [Array(String)] The channels to unsubscribe from.
  #
  # pkg:gem/async-redis#lib/async/redis/context/subscription.rb:67
  def unsubscribe(channels); end
end

# pkg:gem/async-redis#lib/async/redis/context/subscription.rb:14
Async::Redis::Context::Subscription::MESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/async-redis#lib/async/redis/context/subscription.rb:15
Async::Redis::Context::Subscription::PMESSAGE = T.let(T.unsafe(nil), String)

# pkg:gem/async-redis#lib/async/redis/context/subscription.rb:16
Async::Redis::Context::Subscription::SMESSAGE = T.let(T.unsafe(nil), String)

# Context for Redis transaction operations using MULTI/EXEC.
#
# pkg:gem/async-redis#lib/async/redis/context/transaction.rb:13
class Async::Redis::Context::Transaction < ::Async::Redis::Context::Pipeline
  # Initialize a new transaction context.
  # @parameter pool [Pool] The connection pool to use.
  # @parameter arguments [Array] Additional arguments for the transaction.
  #
  # pkg:gem/async-redis#lib/async/redis/context/transaction.rb:17
  def initialize(pool, *arguments); end

  # Discard all queued commands in the transaction.
  #
  # pkg:gem/async-redis#lib/async/redis/context/transaction.rb:38
  def discard; end

  # Execute all queued commands, provided that no watched keys have been modified. It's important to note that even when a command fails, all the other commands in the queue are processed – Redis will not stop the processing of commands.
  #
  # pkg:gem/async-redis#lib/async/redis/context/transaction.rb:33
  def execute; end

  # Begin a transaction block.
  #
  # pkg:gem/async-redis#lib/async/redis/context/transaction.rb:22
  def multi; end

  # Watch keys for changes during the transaction.
  # @parameter keys [Array(String)] The keys to watch.
  #
  # pkg:gem/async-redis#lib/async/redis/context/transaction.rb:28
  def watch(*keys); end
end

# Represents a way to connect to a remote Redis server.
#
# pkg:gem/async-redis#lib/async/redis/endpoint.rb:26
class Async::Redis::Endpoint < ::IO::Endpoint::Generic
  # Create a new endpoint.
  #
  # @parameter url [URI] The URL to connect to.
  # @parameter endpoint [Endpoint] The underlying endpoint to use.
  # @option scheme [String] The scheme to use, e.g. "redis" or "rediss".
  # @option hostname [String] The hostname to connect to (or bind to), overrides the URL hostname (used for SNI).
  # @option port [Integer] The port to bind to, overrides the URL port.
  # @option ssl_context [OpenSSL::SSL::SSLContext] The SSL context to use for secure connections.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:122
  def initialize(url, endpoint = T.unsafe(nil), **options); end

  # Get the address of the underlying endpoint.
  # @returns [String] The address of the endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:164
  def address; end

  # Bind to the endpoint and yield the server socket.
  # @parameter arguments [Array] Arguments to pass to the underlying endpoint bind method.
  # @yields [IO] The bound server socket.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:305
  def bind(*arguments, &block); end

  # Build the underlying endpoint with optional SSL wrapping.
  # @parameter endpoint [IO::Endpoint] Optional base endpoint to wrap.
  # @returns [IO::Endpoint] The built endpoint, potentially wrapped with SSL.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:275
  def build_endpoint(endpoint = T.unsafe(nil)); end

  # Connect to the endpoint and yield the client socket.
  # @yields [IO] The connected client socket.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:311
  def connect(&block); end

  # Get the credentials for authentication.
  # @returns [Array(String) | Nil] The username and password credentials or nil if not specified.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:233
  def credentials; end

  # Get the database number for this endpoint.
  # @returns [Integer | Nil] The database number or nil if not specified.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:221
  def database; end

  # Get the default port for Redis connections.
  # @returns [Integer] The default Redis port (6379).
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:192
  def default_port; end

  # Check if the endpoint is using the default port.
  # @returns [Boolean] True if using the default port.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:198
  def default_port?; end

  # Iterate over each possible endpoint variation.
  # @yields [Endpoint] Each endpoint variant.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:317
  def each; end

  # Get the underlying endpoint, building it if necessary.
  # @returns [IO::Endpoint] The underlying endpoint for connections.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:292
  def endpoint; end

  # Set the underlying endpoint.
  # @parameter endpoint [IO::Endpoint] The endpoint to wrap and use.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:298
  def endpoint=(endpoint); end

  # Check if this endpoint is equal to another.
  # @parameter other [Endpoint] The other endpoint to compare with.
  # @returns [Boolean] True if the endpoints are equal.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:334
  def eql?(other); end

  # Get the hash code for this endpoint.
  # @returns [Integer] The hash code based on the endpoint's key.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:340
  def hash; end

  # The hostname is the server we are connecting to:
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:209
  def hostname; end

  # Convert the endpoint to an inspectable string.
  # @returns [String] An inspectable string representation of the endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:156
  def inspect; end

  # Get the key for hashing and equality comparison.
  # @returns [Array] The key components for this endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:327
  def key; end

  # Check if the endpoint is connecting to localhost.
  # @returns [Boolean] True if connecting to localhost.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:249
  def localhost?; end

  # Get the port for this endpoint.
  # @returns [Integer] The port number.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:204
  def port; end

  # Get the protocol for this endpoint.
  # @returns [Protocol] The protocol instance configured for this endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:176
  def protocol; end

  # Get the scheme for this endpoint.
  # @returns [String] The URL scheme (e.g., "redis" or "rediss").
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:215
  def scheme; end

  # Check if the connection is secure (using TLS).
  # @returns [Boolean] True if the connection uses TLS.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:170
  def secure?; end

  # Get the SSL context for secure connections.
  # @returns [OpenSSL::SSL::SSLContext] The SSL context configured for this endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:264
  def ssl_context; end

  # We don't try to validate peer certificates when talking to localhost because they would always be self-signed.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:254
  def ssl_verify_mode; end

  # Convert the endpoint to a string representation.
  # @returns [String] A string representation of the endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:150
  def to_s; end

  # Convert the endpoint to a URL.
  # @returns [URI] The URL representation of the endpoint.
  #
  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:138
  def to_url; end

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:160
  def url; end

  protected

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:366
  def make_endpoint; end

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:362
  def tcp_endpoint; end

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:346
  def tcp_options; end

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:358
  def unix_endpoint; end

  private

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:225
  def extract_database(path); end

  # pkg:gem/async-redis#lib/async/redis/endpoint.rb:237
  def extract_userinfo(userinfo); end

  class << self
    # Coerce the given object into an endpoint.
    # @parameter url [String | Endpoint] The URL or endpoint to convert.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:106
    def [](object); end

    # Construct an endpoint with a specified scheme, hostname, optional path, and options.
    # If no scheme is provided, it will be auto-detected based on SSL context.
    #
    # @parameter scheme [String, nil] The scheme to use, e.g. "redis" or "rediss". If nil, will auto-detect.
    # @parameter hostname [String] The hostname to connect to (or bind to).
    # @parameter options [Hash] Additional options, passed to {#initialize}.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:77
    def for(scheme, host, port: T.unsafe(nil), database: T.unsafe(nil), **options); end

    # Create a local Redis endpoint.
    # @parameter options [Hash] Additional options for the endpoint.
    # @returns [Endpoint] A local Redis endpoint.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:32
    def local(**options); end

    # Parse a Redis URL string into an endpoint.
    # @parameter string [String] The URL string to parse.
    # @parameter endpoint [Endpoint] Optional underlying endpoint.
    # @parameter options [Hash] Additional options for the endpoint.
    # @returns [Endpoint] The parsed endpoint.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:65
    def parse(string, endpoint = T.unsafe(nil), **options); end

    # Create a remote Redis endpoint.
    # @parameter host [String] The hostname to connect to.
    # @parameter port [Integer] The port to connect to.
    # @parameter options [Hash] Additional options for the endpoint.
    # @returns [Endpoint] A remote Redis endpoint.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:41
    def remote(host, port = T.unsafe(nil), **options); end

    # Create a local Redis endpoint from a UNIX socket path.
    # @parameter path [String] The path to the UNIX socket.
    # @parameter options [Hash] Additional options for the endpoint.
    # @returns [Endpoint] A local Redis endpoint.
    #
    # pkg:gem/async-redis#lib/async/redis/endpoint.rb:50
    def unix(path, **options); end
  end
end

# pkg:gem/async-redis#lib/async/redis/endpoint.rb:27
Async::Redis::Endpoint::LOCALHOST = T.let(T.unsafe(nil), URI::Generic)

# pkg:gem/async-redis#lib/async/redis/endpoint.rb:55
Async::Redis::Endpoint::SCHEMES = T.let(T.unsafe(nil), Hash)

# @namespace
#
# pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:11
module Async::Redis::Protocol; end

# Executes AUTH after the user has established a connection.
#
# pkg:gem/async-redis#lib/async/redis/protocol/authenticated.rb:12
class Async::Redis::Protocol::Authenticated
  # Create a new authenticated protocol.
  #
  # @parameter credentials [Array] The credentials to use for authentication.
  # @parameter protocol [Object] The delegated protocol for connecting.
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/authenticated.rb:21
  def initialize(credentials, protocol = T.unsafe(nil)); end

  # Create a new client and authenticate it.
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/authenticated.rb:29
  def client(stream); end

  # pkg:gem/async-redis#lib/async/redis/protocol/authenticated.rb:26
  def credentials; end
end

# Authentication has failed for some reason.
#
# pkg:gem/async-redis#lib/async/redis/protocol/authenticated.rb:14
class Async::Redis::Protocol::Authenticated::AuthenticationError < ::StandardError; end

# RESP2 protocol implementation for Redis.
#
# pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:13
module Async::Redis::Protocol::RESP2
  class << self
    # Create a new RESP2 client connection.
    # @parameter stream [IO] The stream to use for communication.
    # @returns [Connection] A new RESP2 connection.
    #
    # pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:38
    def client(stream); end
  end
end

# A connection implementation for RESP2 protocol.
#
# pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:15
class Async::Redis::Protocol::RESP2::Connection < ::Protocol::Redis::Connection
  # Get the concurrency level for this connection.
  # @returns [Integer] The concurrency level (1 for RESP2).
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:18
  def concurrency; end

  # Check if the connection can be reused.
  # @returns [Boolean] True if the stream is not closed.
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:30
  def reusable?; end

  # Check if the connection is viable for use.
  # @returns [Boolean] True if the stream is readable.
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/resp2.rb:24
  def viable?; end
end

# Executes AUTH after the user has established a connection.
#
# pkg:gem/async-redis#lib/async/redis/protocol/selected.rb:12
class Async::Redis::Protocol::Selected
  # Create a new authenticated protocol.
  #
  # @parameter index [Integer] The database index to select.
  # @parameter protocol [Object] The delegated protocol for connecting.
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/selected.rb:21
  def initialize(index, protocol = T.unsafe(nil)); end

  # Create a new client and authenticate it.
  #
  # pkg:gem/async-redis#lib/async/redis/protocol/selected.rb:29
  def client(stream); end

  # pkg:gem/async-redis#lib/async/redis/protocol/selected.rb:26
  def index; end
end

# Authentication has failed for some reason.
#
# pkg:gem/async-redis#lib/async/redis/protocol/selected.rb:14
class Async::Redis::Protocol::Selected::SelectionError < ::StandardError; end

# A map that associates one or more ranges with a value for efficient lookup.
#
# pkg:gem/async-redis#lib/async/redis/range_map.rb:10
class Async::Redis::RangeMap
  # Initialize a new RangeMap.
  #
  # pkg:gem/async-redis#lib/async/redis/range_map.rb:12
  def initialize; end

  # Add one or more ranges associated with a value to the map.
  # @parameter ranges [Range | Array(Range)] The ranges to map.
  # @parameter value [Object] The value to associate with the ranges.
  # @returns [Object] The added value.
  #
  # pkg:gem/async-redis#lib/async/redis/range_map.rb:20
  def add(ranges, value); end

  # Clear all ranges from the map.
  #
  # pkg:gem/async-redis#lib/async/redis/range_map.rb:58
  def clear; end

  # Iterate over each mapped value.
  # @yields {|value| ...} Block called for each value.
  #  @parameter value [Object] The value associated with one or more ranges.
  #
  # pkg:gem/async-redis#lib/async/redis/range_map.rb:43
  def each; end

  # Find the value associated with a key within any range.
  # @parameter key [Object] The key to find.
  # @yields {...} Block called if no range contains the key.
  # @returns [Object] The value if found, result of block if given, or nil.
  #
  # pkg:gem/async-redis#lib/async/redis/range_map.rb:30
  def find(key); end

  # Get a random value from the map.
  # @returns [Object] A randomly selected value, or nil if map is empty.
  #
  # pkg:gem/async-redis#lib/async/redis/range_map.rb:51
  def sample; end
end

# A Redis Sentinel client for high availability Redis deployments.
#
# pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:14
class Async::Redis::SentinelClient
  include ::Protocol::Redis::Methods
  include ::Protocol::Redis::Methods::Generic
  include ::Protocol::Redis::Methods::Connection
  include ::Protocol::Redis::Methods::Server
  include ::Protocol::Redis::Methods::Cluster
  include ::Protocol::Redis::Methods::Geospatial
  include ::Protocol::Redis::Methods::Counting
  include ::Protocol::Redis::Methods::Hashes
  include ::Protocol::Redis::Methods::Lists
  include ::Protocol::Redis::Methods::Scripting
  include ::Protocol::Redis::Methods::Sets
  include ::Protocol::Redis::Methods::SortedSets
  include ::Protocol::Redis::Methods::Strings
  include ::Protocol::Redis::Methods::Streams
  include ::Protocol::Redis::Methods::Pubsub
  include ::Async::Redis::Client::Methods

  # Create a new instance of the SentinelClient.
  #
  # @property endpoints [Array(Endpoint)] The list of sentinel endpoints.
  # @property master_name [String] The name of the master instance, defaults to 'mymaster'.
  # @property master_options [Hash] Connection options for master instances.
  # @property slave_options [Hash] Connection options for slave instances (defaults to master_options if not specified).
  # @property role [Symbol] The role of the instance that you want to connect to, either `:master` or `:slave`.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:27
  def initialize(endpoints, master_name: T.unsafe(nil), master_options: T.unsafe(nil), slave_options: T.unsafe(nil), role: T.unsafe(nil), **options); end

  # Close the sentinel client and all connections.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:65
  def close; end

  # Initiate a failover for the specified master.
  # @parameter name [String] The name of the master to failover.
  # @returns [Object] The result of the failover command.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:76
  def failover(name = T.unsafe(nil)); end

  # Get information about a specific master.
  # @parameter name [String] The name of the master.
  # @returns [Hash] The master information hash.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:93
  def master(name = T.unsafe(nil)); end

  # @attribute [String] The name of the master instance.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:41
  def master_name; end

  # Get information about all masters.
  # @returns [Array(Hash)] Array of master information hashes.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:84
  def masters; end

  # Resolve an address for the specified role.
  # @parameter role [Symbol] The role to resolve (:master or :slave).
  # @returns [Endpoint] The resolved endpoint address.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:49
  def resolve_address(role = T.unsafe(nil)); end

  # @attribute [Symbol] The role of the instance that you want to connect to.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:44
  def role; end

  private

  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:137
  def assign_default_tags(tags); end

  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:162
  def available_slaves(reply); end

  # Override the parent method. The only difference is that this one needs to resolve the master/slave address.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:142
  def make_pool(**options); end

  # Resolve the master endpoint address.
  # @returns [Endpoint | Nil] The master endpoint or nil if not found.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:103
  def resolve_master(options = T.unsafe(nil)); end

  # Resolve a slave endpoint address.
  # @returns [Endpoint | Nil] A slave endpoint or nil if not found.
  #
  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:119
  def resolve_slave(options = T.unsafe(nil)); end

  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:174
  def select_slave(available_slaves); end

  # pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:154
  def sentinels; end
end

# pkg:gem/async-redis#lib/async/redis/sentinel_client.rb:15
Async::Redis::SentinelClient::DEFAULT_MASTER_NAME = T.let(T.unsafe(nil), String)

# Legacy.
#
# pkg:gem/async-redis#lib/async/redis/client.rb:24
Async::Redis::ServerError = Protocol::Redis::ServerError

# pkg:gem/async-redis#lib/async/redis/version.rb:8
Async::Redis::VERSION = T.let(T.unsafe(nil), String)
