# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-helpers-sql-processor` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-helpers-sql-processor`.


# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:9
module OpenTelemetry; end

# The helpers module contains functionality shared across multiple
# instrumentation libraries
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:10
module OpenTelemetry::Helpers; end

# SQL processing utilities for OpenTelemetry instrumentation.
#
# This module provides a unified interface for SQL processing operations
# commonly needed in database adapter instrumentation, including SQL obfuscation
# and SQL comment-based trace context propagation.
#
# @api public
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:11
module OpenTelemetry::Helpers::SqlProcessor
  private

  # This is a SQL obfuscation utility intended for use in database adapter instrumentation. It uses the {Obfuscator} module.
  #
  # @param sql [String] The SQL to obfuscate.
  # @param obfuscation_limit [optional Integer] the length at which the SQL string will not be obfuscated
  # @param adapter [optional Symbol] the type of database adapter calling the method. `:default`, `:mysql`, `:postgres`, `:sqlite`, `:oracle`, `:cassandra` are supported.
  # @return [String] The SQL query string where the values are replaced with "?". When the sql statement exceeds the obfuscation limit
  #  the first matched pair from the SQL statement will be returned, with an appended truncation message. If truncation is unsuccessful,
  #  a string describing the error will be returned.
  #
  # @api public
  #
  # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor.rb:33
  def obfuscate_sql(sql, obfuscation_limit: T.unsafe(nil), adapter: T.unsafe(nil)); end

  class << self
    # This is a SQL obfuscation utility intended for use in database adapter instrumentation. It uses the {Obfuscator} module.
    #
    # @param sql [String] The SQL to obfuscate.
    # @param obfuscation_limit [optional Integer] the length at which the SQL string will not be obfuscated
    # @param adapter [optional Symbol] the type of database adapter calling the method. `:default`, `:mysql`, `:postgres`, `:sqlite`, `:oracle`, `:cassandra` are supported.
    # @return [String] The SQL query string where the values are replaced with "?". When the sql statement exceeds the obfuscation limit
    #  the first matched pair from the SQL statement will be returned, with an appended truncation message. If truncation is unsuccessful,
    #  a string describing the error will be returned.
    #
    # @api public
    #
    # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor.rb:33
    def obfuscate_sql(sql, obfuscation_limit: T.unsafe(nil), adapter: T.unsafe(nil)); end
  end
end

# This module contains SQL obfuscation behavior to share with
# instrumentation for specific database adapters.
# The class uses code from: https://github.com/newrelic/newrelic-ruby-agent/blob/1fca78cc7a087421ad58088d8bea72c0362bc62f/lib/new_relic/agent/database/obfuscation_helpers.rb
#
# To use this in your instrumentation, the `Instrumentation` class for
# your gem must contain configuration options for:
#  * `:db_statement`
#    Example:
#    `option :db_statement, default: :include, validate: %I[omit include obfuscate]`
#  * `:obfuscation_limit`
#    Example:
#    `option :obfuscation_limit, default: 2000, validate: :integer`
#
# If you want to add support for a new adapter, update the following
# constants to include keys for your adapter:
#  * DIALECT_COMPONENTS
#  * CLEANUP_REGEX
# You must also add a new constant that uses `generate_regex` with your
# adapter's dialect components that is named like
# `<ADAPTER>_COMPONENTS_REGEX`, such as: `MYSQL_COMPONENTS_REGEX`.
#
# @api public
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:35
module OpenTelemetry::Helpers::SqlProcessor::Obfuscator
  private

  # @api private
  #
  # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:83
  def generate_regex(dialect); end

  # Internal implementation of SQL obfuscation.
  # Use SqlProcessor.obfuscate_sql for the public API.
  #
  # @api private
  #
  # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:99
  def obfuscate_sql(sql, obfuscation_limit: T.unsafe(nil), adapter: T.unsafe(nil)); end

  class << self
    # @api private
    #
    # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:83
    def generate_regex(dialect); end

    # Internal implementation of SQL obfuscation.
    # Use SqlProcessor.obfuscate_sql for the public API.
    #
    # @api private
    #
    # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:99
    def obfuscate_sql(sql, obfuscation_limit: T.unsafe(nil), adapter: T.unsafe(nil)); end
  end
end

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:92
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::CASSANDRA_COMPONENTS_REGEX = T.let(T.unsafe(nil), Regexp)

# We use these to check whether the query contains any quote characters
# after obfuscation. If so, that's a good indication that the original
# query was malformed, and so our obfuscation can't reliably find
# literals. In such a case, we'll replace the entire query with a
# placeholder.
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:73
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::CLEANUP_REGEX = T.let(T.unsafe(nil), Hash)

# From: https://github.com/newrelic/newrelic-ruby-agent/blob/1fca78cc7a087421ad58088d8bea72c0362bc62f/lib/new_relic/agent/database/obfuscation_helpers.rb
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:39
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::COMPONENTS_REGEX_MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:88
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::DEFAULT_COMPONENTS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:52
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::DIALECT_COMPONENTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:89
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::MYSQL_COMPONENTS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:93
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::ORACLE_COMPONENTS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:66
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::PLACEHOLDER = T.let(T.unsafe(nil), String)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:90
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::POSTGRES_COMPONENTS_REGEX = T.let(T.unsafe(nil), Regexp)

# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/obfuscator.rb:91
OpenTelemetry::Helpers::SqlProcessor::Obfuscator::SQLITE_COMPONENTS_REGEX = T.let(T.unsafe(nil), Regexp)

# SqlCommenter provides SQL comment-based trace context propagation
# according to the SQL Commenter specification.
#
# This module implements a propagator interface compatible with Vitess,
# allowing it to be used as a drop-in replacement.
#
# @api public
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/commenter.rb:19
module OpenTelemetry::Helpers::SqlProcessor::SqlCommenter
  extend ::OpenTelemetry::Helpers::SqlProcessor::SqlCommenter

  # Returns the SqlQueryPropagator module for stateless propagation
  #
  # @return [Module] The SqlQueryPropagator module
  #
  # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/commenter.rb:86
  def sql_query_propagator; end
end

# SqlQueryPropagator propagates trace context using SQL comments
# according to the SQL Commenter specification.
#
# This propagator implements the same interface as the Vitess propagator
# and can be used as a drop-in replacement.
#
# @example
#   propagator = OpenTelemetry::Helpers::SqlProcessor::SqlCommenter.sql_query_propagator
#   sql = "SELECT * FROM users"
#   propagator.inject(sql, context: current_context)
#   # => "SELECT * FROM users /*traceparent='00-...',tracestate='...'*/"
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/commenter.rb:62
module OpenTelemetry::Helpers::SqlProcessor::SqlCommenter::SqlQueryPropagator
  extend ::OpenTelemetry::Helpers::SqlProcessor::SqlCommenter::SqlQueryPropagator

  # Injects trace context into a SQL query as a comment
  #
  # @param carrier [String] The SQL query string to inject context into
  # @param context [optional, Context] The context to inject. Defaults to current context.
  # @param setter [optional, #set] The setter to use for appending the comment.
  #   Defaults to SqlQuerySetter.
  # @return [nil]
  #
  # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/commenter.rb:72
  def inject(carrier, context: T.unsafe(nil), setter: T.unsafe(nil)); end
end

# SqlQuerySetter is responsible for formatting trace context as SQL comments
# and appending them to SQL queries according to the SQL Commenter specification.
#
# Format: /*key='value',key2='value2'*/
# Values are URL-encoded per the SQL Commenter spec
#
# pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/commenter.rb:27
module OpenTelemetry::Helpers::SqlProcessor::SqlCommenter::SqlQuerySetter
  extend ::OpenTelemetry::Helpers::SqlProcessor::SqlCommenter::SqlQuerySetter

  # Appends trace context as a SQL comment to the carrier (SQL query string)
  #
  # @param carrier [String] The SQL query string to modify
  # @param headers [Hash] Hash of trace context headers (e.g., {'traceparent' => '00-...'})
  #
  # pkg:gem/opentelemetry-helpers-sql-processor#lib/opentelemetry/helpers/sql_processor/commenter.rb:34
  def set(carrier, headers); end
end
