# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `protocol-redis` gem.
# Please instead update this file by running `bin/tapioca gem protocol-redis`.


# @namespace
# Released under the MIT License.
# Copyright, 2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2025-2026, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2023, by Nick Burwell.
# Copyright, 2024-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Copyright, 2023, by Troex Nevelin.
# Copyright, 2023, by Nick Burwell.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Copyright, 2020, by Salim Semaoune.
# Released under the MIT License.
# Copyright, 2020-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2020-2025, by Samuel Williams.
# Copyright, 2023, by Nick Burwell.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Copyright, 2020, by David Ortiz.
# Released under the MIT License.
# Copyright, 2020-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2020, by Dimitry Chopey.
# Copyright, 2020-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2020-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2019-2025, by Samuel Williams.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:9
module Protocol; end

# @namespace
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:10
module Protocol::Redis; end

# @namespace
#
# pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:8
module Protocol::Redis::Cluster; end

# A collection of methods for interacting with Redis in cluster mode.
#
# pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:9
module Protocol::Redis::Cluster::Methods
  include ::Protocol::Redis::Cluster::Methods::Generic
  include ::Protocol::Redis::Cluster::Methods::Pubsub
  include ::Protocol::Redis::Cluster::Methods::Streams
  include ::Protocol::Redis::Cluster::Methods::Strings

  class << self
    # Includes all Redis methods into the given class.
    #
    # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods.rb:18
    def included(klass); end
  end
end

# Provides generic Redis commands for cluster environments.
# These methods distribute operations across cluster nodes based on key slots.
#
# pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:12
module Protocol::Redis::Cluster::Methods::Generic
  # Delete one or more keys from the cluster.
  # Uses the appropriate client(s) for each key's slot.
  # @parameter keys [Array(String)] The keys to delete.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @parameter options [Hash] Additional options passed to the client.
  # @returns [Integer] The number of keys deleted.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:19
  def del(*keys, role: T.unsafe(nil), **options); end

  # Check existence of one or more keys in the cluster.
  # @parameter keys [Array(String)] The keys to check.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @parameter options [Hash] Additional options passed to the client.
  # @returns [Integer] The number of keys existing.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:36
  def exists(*keys, role: T.unsafe(nil), **options); end

  # Get the value of a single key from the cluster.
  # @parameter key [String] The key to fetch.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @parameter options [Hash] Additional options passed to the client.
  # @returns [Object] The value for the given key.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:74
  def get(key, role: T.unsafe(nil), **options); end

  # Get the values of multiple keys from the cluster.
  # @parameter keys [Array(String)] The keys to fetch.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @parameter options [Hash] Additional options passed to the client.
  # @returns [Array] The values for the given keys, in order.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:53
  def mget(*keys, role: T.unsafe(nil), **options); end

  # Set the value of a single key in the cluster.
  # @parameter key [String] The key to set.
  # @parameter value [Object] The value to set.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @parameter options [Hash] Additional options passed to the client.
  # @returns [String | Boolean] Status reply or `true`/`false` depending on client implementation.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/generic.rb:87
  def set(key, value, role: T.unsafe(nil), **options); end
end

# Provides Redis Pub/Sub commands for cluster environments.
# Uses sharded pub/sub by default for optimal cluster performance.
#
# pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/pubsub.rb:12
module Protocol::Redis::Cluster::Methods::Pubsub
  # Post a message to a channel using cluster-optimized sharded publish.
  # Routes the message directly to the appropriate shard based on the channel name.
  # @parameter channel [String] The channel name.
  # @parameter message [String] The message to publish.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The number of clients that received the message.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/pubsub.rb:19
  def publish(channel, message, role: T.unsafe(nil)); end
end

# Provides Redis Streams commands for cluster environments.
# Stream operations are routed to the appropriate shard based on the stream key.
#
# pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:12
module Protocol::Redis::Cluster::Methods::Streams
  # Acknowledge processed messages in a consumer group.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Group name and message IDs.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] Number of messages acknowledged.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:173
  def xack(key, *arguments, role: T.unsafe(nil)); end

  # Append a new entry to a stream.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Additional XADD arguments (ID and field-value pairs).
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] The ID of the added entry.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:37
  def xadd(key, *arguments, role: T.unsafe(nil)); end

  # Change ownership of messages in a consumer group.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Group, consumer, min-idle-time, and message IDs.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] Claimed messages.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:185
  def xclaim(key, *arguments, role: T.unsafe(nil)); end

  # Remove specified entries from the stream.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Entry IDs to remove.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] Number of entries actually deleted.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:61
  def xdel(key, *arguments, role: T.unsafe(nil)); end

  # Create, destroy, and manage consumer groups.
  # @parameter arguments [Array] XGROUP command arguments.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String | Integer] Command result.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:128
  def xgroup(*arguments, role: T.unsafe(nil)); end

  # Get information on streams and consumer groups.
  # @parameter arguments [Array] XINFO command arguments (subcommand and stream key).
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] Stream information.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:17
  def xinfo(*arguments, role: T.unsafe(nil)); end

  # Return the number of entries in a stream.
  # @parameter key [String] The stream key.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] Number of entries in the stream.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:96
  def xlen(key, role: T.unsafe(nil)); end

  # Get information about pending messages in a consumer group.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Group name and optional consumer/range parameters.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] Pending message information.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:197
  def xpending(key, *arguments, role: T.unsafe(nil)); end

  # Return a range of elements in a stream.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Range parameters (start, end, optional COUNT).
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] Stream entries in the specified range.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:73
  def xrange(key, *arguments, role: T.unsafe(nil)); end

  # Read new entries from multiple streams.
  # Note: In cluster mode, all streams in a single XREAD must be on the same shard.
  # @parameter arguments [Array] XREAD arguments including STREAMS keyword and stream keys/IDs.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] New entries from the specified streams.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:108
  def xread(*arguments, role: T.unsafe(nil)); end

  # Read new entries from streams using a consumer group.
  # @parameter arguments [Array] XREADGROUP arguments.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] Entries for the consumer group.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:153
  def xreadgroup(*arguments, role: T.unsafe(nil)); end

  # Return a range of elements in a stream in reverse order.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Range parameters (end, start, optional COUNT).
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] Stream entries in reverse order.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:85
  def xrevrange(key, *arguments, role: T.unsafe(nil)); end

  # Trim the stream to a certain size.
  # @parameter key [String] The stream key.
  # @parameter arguments [Array] Trim strategy and parameters.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] Number of entries removed.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/streams.rb:49
  def xtrim(key, *arguments, role: T.unsafe(nil)); end
end

# Provides Redis String commands for cluster environments.
# String operations are routed to the appropriate shard based on the key.
#
# pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:12
module Protocol::Redis::Cluster::Methods::Strings
  # Append a value to a key.
  # @parameter key [String] The key to append to.
  # @parameter value [String] The value to append.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The length of the string after the append operation.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:18
  def append(key, value, role: T.unsafe(nil)); end

  # Count set bits in a string.
  # @parameter key [String] The key to count bits in.
  # @parameter range [Array] Optional start and end positions.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The number of set bits.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:30
  def bitcount(key, *range, role: T.unsafe(nil)); end

  # Decrement the integer value of a key by one.
  # @parameter key [String] The key to decrement.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The value after decrementing.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:41
  def decr(key, role: T.unsafe(nil)); end

  # Decrement the integer value of a key by the given number.
  # @parameter key [String] The key to decrement.
  # @parameter decrement [Integer] The amount to decrement by.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The value after decrementing.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:53
  def decrby(key, decrement, role: T.unsafe(nil)); end

  # Get the value of a key.
  # @parameter key [String] The key to get.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String | nil] The value, or `nil` if key doesn't exist.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:64
  def get(key, role: T.unsafe(nil)); end

  # Get the bit value at offset in the string value stored at key.
  # @parameter key [String] The key to get bit from.
  # @parameter offset [Integer] The bit offset.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The bit value (0 or 1).
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:76
  def getbit(key, offset, role: T.unsafe(nil)); end

  # Get a substring of the string stored at a key.
  # @parameter key [String] The key to get range from.
  # @parameter start_index [Integer] The start position.
  # @parameter end_index [Integer] The end position.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] The substring.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:89
  def getrange(key, start_index, end_index, role: T.unsafe(nil)); end

  # Set the string value of a key and return its old value.
  # @parameter key [String] The key to set.
  # @parameter value [String] The new value.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String | nil] The old value, or `nil` if key didn't exist.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:101
  def getset(key, value, role: T.unsafe(nil)); end

  # Increment the integer value of a key by one.
  # @parameter key [String] The key to increment.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The value after incrementing.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:112
  def incr(key, role: T.unsafe(nil)); end

  # Increment the integer value of a key by the given amount.
  # @parameter key [String] The key to increment.
  # @parameter increment [Integer] The amount to increment by.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The value after incrementing.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:124
  def incrby(key, increment, role: T.unsafe(nil)); end

  # Increment the float value of a key by the given amount.
  # @parameter key [String] The key to increment.
  # @parameter increment [Float] The amount to increment by.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] The value after incrementing (as string).
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:136
  def incrbyfloat(key, increment, role: T.unsafe(nil)); end

  # Get the values of all the given keys.
  # Uses the cluster-aware multi-key handling from generic methods.
  # @parameter keys [Array(String)] The keys to get.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Array] The values for the given keys, in order.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:148
  def mget(*keys, role: T.unsafe(nil)); end

  # Set multiple keys to multiple values.
  # Redis will return a CROSSSLOT error if keys span multiple slots.
  # @parameter pairs [Hash] The key-value pairs to set.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] Status reply.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:169
  def mset(pairs, role: T.unsafe(nil)); end

  # Set multiple keys to multiple values, only if none exist.
  # Redis will return a CROSSSLOT error if keys span multiple slots.
  # @parameter pairs [Hash] The key-value pairs to set.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] 1 if all keys were set, 0 otherwise.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:187
  def msetnx(pairs, role: T.unsafe(nil)); end

  # Set the value and expiration in milliseconds of a key.
  # @parameter key [String] The key to set.
  # @parameter milliseconds [Integer] The expiration time in milliseconds.
  # @parameter value [String] The value to set.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] Status reply.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:204
  def psetex(key, milliseconds, value, role: T.unsafe(nil)); end

  # Set the string value of a key.
  # @parameter key [String] The key to set.
  # @parameter value [String] The value to set.
  # @parameter update [Boolean | nil] If `true`, only update existing keys. If `false`, only set new keys.
  # @parameter seconds [Integer | nil] Expiration time in seconds.
  # @parameter milliseconds [Integer | nil] Expiration time in milliseconds.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] Status reply.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:219
  def set(key, value, update: T.unsafe(nil), seconds: T.unsafe(nil), milliseconds: T.unsafe(nil), role: T.unsafe(nil)); end

  # Set or clear the bit at offset in the string value stored at key.
  # @parameter key [String] The key to modify.
  # @parameter offset [Integer] The bit offset.
  # @parameter value [Integer] The bit value (0 or 1).
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The original bit value.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:248
  def setbit(key, offset, value, role: T.unsafe(nil)); end

  # Set the value and expiration of a key.
  # @parameter key [String] The key to set.
  # @parameter seconds [Integer] The expiration time in seconds.
  # @parameter value [String] The value to set.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [String] Status reply.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:261
  def setex(key, seconds, value, role: T.unsafe(nil)); end

  # Set the value of a key, only if the key does not exist.
  # @parameter key [String] The key to set.
  # @parameter value [String] The value to set.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Boolean] `true` if the key was set, `false` otherwise.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:273
  def setnx(key, value, role: T.unsafe(nil)); end

  # Overwrite part of a string at key starting at the specified offset.
  # @parameter key [String] The key to modify.
  # @parameter offset [Integer] The offset to start overwriting at.
  # @parameter value [String] The value to write.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The length of the string after modification.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:286
  def setrange(key, offset, value, role: T.unsafe(nil)); end

  # Get the length of the value stored in a key.
  # @parameter key [String] The key to get length of.
  # @parameter role [Symbol] The role of node to use (`:master` or `:slave`).
  # @returns [Integer] The length of the string value, or 0 if key doesn't exist.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/cluster/methods/strings.rb:297
  def strlen(key, role: T.unsafe(nil)); end
end

# Represents a Redis protocol connection handling low-level communication.
#
# pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:11
class Protocol::Redis::Connection
  # Initialize a new connection with the provided stream.
  # @parameter stream [IO] The underlying stream for communication.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:16
  def initialize(stream); end

  # Close the underlying stream connection.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:29
  def close; end

  # Check if the connection is closed.
  # @returns [Boolean] True if the connection is closed.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:45
  def closed?; end

  # @attr [Integer] Number of requests sent.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:26
  def count; end

  # Flush any buffered data to the stream.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:39
  def flush; end

  # Read data of specified length from the stream.
  # @parameter length [Integer] The number of bytes to read.
  # @returns [String] The data read from the stream.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:92
  def read_data(length); end

  # Read and parse a Redis object from the stream.
  # @returns [Object] The parsed Redis object (String, Array, Integer, or nil).
  # @raises [ServerError] If the server returns an error response.
  # @raises [EOFError] If the stream reaches end of file.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:105
  def read_object; end

  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:155
  def read_response; end

  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:23
  def stream; end

  # Write a Redis array to the stream.
  # @parameter array [Array] The array to write.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:81
  def write_array(array); end

  # Write a Redis object to the stream.
  # @parameter object [Object] The object to write (String, Array, Integer, or object with to_redis method).
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:64
  def write_object(object); end

  # The redis server doesn't want actual objects (e.g. integers) but only bulk strings. So, we inline it for performance.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:50
  def write_request(arguments); end

  private

  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:174
  def read_line; end

  # In the case of Redis, we do not want to perform a flush in every line,
  # because each Redis command contains several lines. Flushing once per
  # command is more efficient because it avoids unnecessary writes to the
  # socket.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:163
  def write_lines(*arguments); end

  class << self
    # Create a new client connection instance.
    #
    # pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:35
    def client(*_arg0); end
  end
end

# pkg:gem/protocol-redis#lib/protocol/redis/connection.rb:12
Protocol::Redis::Connection::CRLF = T.let(T.unsafe(nil), String)

# Represents a general Redis protocol error.
#
# pkg:gem/protocol-redis#lib/protocol/redis/error.rb:9
class Protocol::Redis::Error < ::StandardError; end

# A collection of methods for interacting with Redis.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:11
module Protocol::Redis::Methods
  include ::Protocol::Redis::Methods::Generic
  include ::Protocol::Redis::Methods::Connection
  include ::Protocol::Redis::Methods::Server
  include ::Protocol::Redis::Methods::Cluster
  include ::Protocol::Redis::Methods::Geospatial
  include ::Protocol::Redis::Methods::Counting
  include ::Protocol::Redis::Methods::Hashes
  include ::Protocol::Redis::Methods::Lists
  include ::Protocol::Redis::Methods::Scripting
  include ::Protocol::Redis::Methods::Sets
  include ::Protocol::Redis::Methods::SortedSets
  include ::Protocol::Redis::Methods::Strings
  include ::Protocol::Redis::Methods::Streams
  include ::Protocol::Redis::Methods::Pubsub

  class << self
    # Includes all Redis methods into the given class.
    #
    # pkg:gem/protocol-redis#lib/protocol/redis/methods.rb:32
    def included(klass); end
  end
end

# Methods for managing Redis clusters.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/cluster.rb:11
module Protocol::Redis::Methods::Cluster
  # Sends `ASKING` command to random node and returns its reply.
  # See <https://redis.io/commands/asking/> for more details.
  #
  # @returns [String] `'OK'`
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/cluster.rb:26
  def asking; end

  # Sends the `CLUSTER *` command to random node and returns its reply.
  # See <https://redis.io/commands/cluster-addslots/> for more details.
  # @parameter subcommand [String, Symbol] the subcommand of cluster command
  #   e.g. `:addslots`, `:delslots`, `:nodes`, `:replicas`, `:info`
  #
  # @returns [Object] depends on the subcommand provided
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/cluster.rb:18
  def cluster(subcommand, *arguments); end
end

# Methods for managing Redis connections.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/connection.rb:10
module Protocol::Redis::Methods::Connection
  # Authenticate to the server.
  # See <https://redis.io/commands/auth> for more details.
  # @parameter username [String] Optional username, if Redis ACLs are used.
  # @parameter password [String] Required password.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/connection.rb:15
  def auth(*arguments); end

  # Echo the given string.
  # See <https://redis.io/commands/echo> for more details.
  # @parameter message [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/connection.rb:22
  def echo(message); end

  # Ping the server.
  # See <https://redis.io/commands/ping> for more details.
  # @parameter message [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/connection.rb:29
  def ping(message); end

  # Close the connection.
  # See <https://redis.io/commands/quit> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/connection.rb:35
  def quit; end
end

# Methods for managing Redis HyperLogLogs.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/counting.rb:10
module Protocol::Redis::Methods::Counting
  # Adds the specified elements to the specified HyperLogLog. O(1) to add every element.
  # See <https://redis.io/commands/pfadd> for more details.
  # @parameter key [Key]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/counting.rb:15
  def pfadd(key, element, *elements); end

  # Return the approximated cardinality of the set(s) observed by the HyperLogLog at key(s). O(1) with a very small average constant time when called with a single key. O(N) with N being the number of keys, and much bigger constant times, when called with multiple keys.
  # See <https://redis.io/commands/pfcount> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/counting.rb:22
  def pfcount(key, *keys); end

  # Merge N different HyperLogLogs into a single one. O(N) to merge N HyperLogLogs, but with high constant times.
  # See <https://redis.io/commands/pfmerge> for more details.
  # @parameter destkey [Key]
  # @parameter sourcekey [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/counting.rb:30
  def pfmerge(destkey, sourcekey, *sourcekeys); end
end

# Methods for interacting with Redis keys.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:13
module Protocol::Redis::Methods::Generic
  # Delete a key. O(N) where N is the number of keys that will be removed. When a key to remove holds a value other than a string, the individual complexity for this key is O(M) where M is the number of elements in the list, set, sorted set or hash. Removing a single key that holds a string value is O(1).
  # See <https://redis.io/commands/del> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:17
  def del(*keys); end

  # Return a serialized version of the value stored at the specified key. O(1) to access the key and additional O(N*M) to serialized it, where N is the number of Redis objects composing the value and M their average size. For small string values the time complexity is thus O(1)+O(1*M) where M is small, so simply O(1).
  # See <https://redis.io/commands/dump> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:26
  def dump(key); end

  # Determine if a key exists. O(1).
  # See <https://redis.io/commands/exists> for more details.
  # @parameter key [Key]
  # @returns [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:34
  def exists(key, *keys); end

  # Boolean oversion of `exists`
  # @parameter key [Key]
  # @returns [Boolean]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:41
  def exists?(key, *keys); end

  # Set a key's time to live in seconds. O(1).
  # See <https://redis.io/commands/expire> for more details.
  # @parameter key [Key]
  # @parameter seconds [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:49
  def expire(key, seconds); end

  # Set the expiration for a key as a UNIX timestamp. O(1).
  # See <https://redis.io/commands/expireat> for more details.
  # @parameter key [Key]
  # @parameter timestamp [Posix time]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:57
  def expireat(key, time); end

  # Find all keys matching the given pattern. O(N) with N being the number of keys in the database, under the assumption that the key names in the database and the given pattern have limited length.
  # See <https://redis.io/commands/keys> for more details.
  # @parameter pattern [Pattern]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:71
  def keys(pattern); end

  # Atomically transfer a key from a Redis instance to another one. This command actually executes a DUMP+DEL in the source instance, and a RESTORE in the target instance. See the pages of these commands for time complexity. Also an O(N) data transfer between the two instances is performed.
  # See <https://redis.io/commands/migrate> for more details.
  # @parameter host [String]
  # @parameter port [String]
  # @parameter key [Enum]
  # @parameter destination-db [Integer]
  # @parameter timeout [Integer]
  # @parameter copy [Enum]
  # @parameter replace [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:84
  def migrate(host, port, destination = T.unsafe(nil), keys:, timeout: T.unsafe(nil), copy: T.unsafe(nil), replace: T.unsafe(nil), auth: T.unsafe(nil)); end

  # Move a key to another database. O(1).
  # See <https://redis.io/commands/move> for more details.
  # @parameter key [Key]
  # @parameter db [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:120
  def move(key, db); end

  # Inspect the internals of Redis objects. O(1) for all the currently implemented subcommands.
  # See <https://redis.io/commands/object> for more details.
  # @parameter subcommand [String]
  # @parameter arguments [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:128
  def object(subcommand, *arguments); end

  # Remove the expiration from a key. O(1).
  # See <https://redis.io/commands/persist> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:135
  def persist(key); end

  # Set a key's time to live in milliseconds. O(1).
  # See <https://redis.io/commands/pexpire> for more details.
  # @parameter key [Key]
  # @parameter milliseconds [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:143
  def pexpire(key, milliseconds); end

  # Set the expiration for a key as a UNIX timestamp specified in milliseconds. O(1).
  # See <https://redis.io/commands/pexpireat> for more details.
  # @parameter key [Key]
  # @parameter milliseconds-timestamp [Posix time]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:151
  def pexpireat(key, time); end

  # Get the time to live for a key in milliseconds. O(1).
  # See <https://redis.io/commands/pttl> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:165
  def pttl(key); end

  # Return a random key from the keyspace. O(1).
  # See <https://redis.io/commands/randomkey> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:171
  def randomkey; end

  # Rename a key. O(1).
  # See <https://redis.io/commands/rename> for more details.
  # @parameter key [Key]
  # @parameter newkey [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:179
  def rename(key, new_key); end

  # Rename a key, only if the new key does not exist. O(1).
  # See <https://redis.io/commands/renamenx> for more details.
  # @parameter key [Key]
  # @parameter newkey [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:187
  def renamenx(key, new_key); end

  # Create a key using the provided serialized value, previously obtained using DUMP. O(1) to create the new key and additional O(N*M) to reconstruct the serialized value, where N is the number of Redis objects composing the value and M their average size. For small string values the time complexity is thus O(1)+O(1*M) where M is small, so simply O(1). However for sorted set values the complexity is O(N*M*log(N)) because inserting values into sorted sets is O(log(N)).
  # See <https://redis.io/commands/restore> for more details.
  # @parameter key [Key]
  # @parameter ttl [Integer]
  # @parameter serialized-value [String]
  # @parameter replace [Enum]
  # @parameter absttl [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:198
  def restore(key, serialized_value, ttl = T.unsafe(nil)); end

  # Incrementally iterate the keys space. O(1) for every call. O(N) for a complete iteration, including enough command calls for the cursor to return back to 0. N is the number of elements inside the collection.
  # See <https://redis.io/commands/scan> for more details.
  # @parameter cursor [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:205
  def scan(cursor, match: T.unsafe(nil), count: T.unsafe(nil), type: T.unsafe(nil)); end

  # Sort the elements in a list, set or sorted set. O(N+M*log(M)) where N is the number of elements in the list or set to sort, and M the number of returned elements. When the elements are not sorted, complexity is currently O(N) as there is a copy step that will be avoided in next releases.
  # See <https://redis.io/commands/sort> for more details.
  # @parameter key [Key]
  # @parameter order [Enum]
  # @parameter sorting [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:228
  def sort(key, by: T.unsafe(nil), offset: T.unsafe(nil), count: T.unsafe(nil), get: T.unsafe(nil), order: T.unsafe(nil), alpha: T.unsafe(nil), store: T.unsafe(nil)); end

  # Alters the last access time of a key(s). Returns the number of existing keys specified. O(N) where N is the number of keys that will be touched.
  # See <https://redis.io/commands/touch> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:261
  def touch(key, *keys); end

  # Get the time to live for a key. O(1).
  # See <https://redis.io/commands/ttl> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:268
  def ttl(key); end

  # Determine the type stored at key. O(1).
  # See <https://redis.io/commands/type> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:275
  def type(key); end

  # Delete a key asynchronously in another thread. Otherwise it is just as DEL, but non blocking. O(1) for each key removed regardless of its size. Then the command does O(N) work in a different thread in order to reclaim memory, where N is the number of allocations the deleted objects where composed of.
  # See <https://redis.io/commands/unlink> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:282
  def unlink(key); end

  # Wait for the synchronous replication of all the write commands sent in the context of the current connection. O(1).
  # See <https://redis.io/commands/wait> for more details.
  # @parameter numreplicas [Integer]
  # @parameter timeout [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/generic.rb:290
  def wait(numreplicas, timeout = T.unsafe(nil)); end
end

# Methods for managing Redis geospatial indexes.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:10
module Protocol::Redis::Methods::Geospatial
  # Add one or more geospatial items in the geospatial index represented using a sorted set. O(log(N)) for each item added, where N is the number of elements in the sorted set.
  # See <https://redis.io/commands/geoadd> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:14
  def geoadd(key, longitude, latitude, member, *arguments); end

  # Returns the distance between two members of a geospatial index. O(log(N)).
  # See <https://redis.io/commands/geodist> for more details.
  # @parameter key [Key]
  # @parameter member1 [String]
  # @parameter member2 [String]
  # @parameter unit [Enum] Distance scale to use, one of "m" (meters), "km" (kilometers), "mi" (miles) or "ft" (feet).
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:40
  def geodist(key, from, to, unit = T.unsafe(nil)); end

  # Returns members of a geospatial index as standard geohash strings. O(log(N)) for each member requested, where N is the number of elements in the sorted set.
  # See <https://redis.io/commands/geohash> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:22
  def geohash(key, member, *members); end

  # Returns longitude and latitude of members of a geospatial index. O(log(N)) for each member requested, where N is the number of elements in the sorted set.
  # See <https://redis.io/commands/geopos> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:30
  def geopos(key, member, *members); end

  # Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a point. O(N+log(M)) where N is the number of elements inside the bounding box of the circular area delimited by center and radius and M is the number of items inside the index.
  # See <https://redis.io/commands/georadius> for more details.
  # @parameter key [Key]
  # @parameter longitude [Double]
  # @parameter latitude [Double]
  # @parameter radius [Double]
  # @parameter unit [Enum]
  # @parameter count [Integer] Limit the number of results to at most this many.
  # @parameter order [Symbol] `:ASC` Sort returned items from the nearest to the farthest, relative to the center. `:DESC` Sort returned items from the farthest to the nearest, relative to the center.
  # @parameter with_coordinates [Boolean] Also return the longitude,latitude coordinates of the matching items.
  # @parameter with_distance [Boolean] Also return the distance of the returned items from the specified center. The distance is returned in the same unit as the unit specified as the radius argument of the command.
  # @parameter with_hash [Boolean] Also return the raw geohash-encoded sorted set score of the item, in the form of a 52 bit unsigned integer. This is only useful for low level hacks or debugging and is otherwise of little interest for the general user.
  # @parameter store [Key]
  # @parameter store_distance [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:58
  def georadius(key, longitude, latitude, radius, unit = T.unsafe(nil), with_coordinates: T.unsafe(nil), with_distance: T.unsafe(nil), with_hash: T.unsafe(nil), count: T.unsafe(nil), order: T.unsafe(nil), store: T.unsafe(nil), store_distance: T.unsafe(nil)); end

  # Query a sorted set representing a geospatial index to fetch members matching a given maximum distance from a member. O(N+log(M)) where N is the number of elements inside the bounding box of the circular area delimited by center and radius and M is the number of items inside the index.
  # See <https://redis.io/commands/georadiusbymember> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  # @parameter radius [Double]
  # @parameter unit [Enum]
  # @parameter count [Integer] Limit the number of results to at most this many.
  # @parameter order [Symbol] `:ASC` Sort returned items from the nearest to the farthest, relative to the center. `:DESC` Sort returned items from the farthest to the nearest, relative to the center.
  # @parameter with_coordinates [Boolean] Also return the longitude,latitude coordinates of the matching items.
  # @parameter with_distance [Boolean] Also return the distance of the returned items from the specified center. The distance is returned in the same unit as the unit specified as the radius argument of the command.
  # @parameter with_hash [Boolean] Also return the raw geohash-encoded sorted set score of the item, in the form of a 52 bit unsigned integer. This is only useful for low level hacks or debugging and is otherwise of little interest for the general user.
  # @parameter store [Key]
  # @parameter store_distance [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/geospatial.rb:114
  def georadiusbymember(key, member, radius, unit = T.unsafe(nil), with_coordinates: T.unsafe(nil), with_distance: T.unsafe(nil), with_hash: T.unsafe(nil), count: T.unsafe(nil), order: T.unsafe(nil), store: T.unsafe(nil), store_distance: T.unsafe(nil)); end
end

# Methods for managing Redis hashes.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:12
module Protocol::Redis::Methods::Hashes
  # Delete one or more hash fields. O(N) where N is the number of fields to be removed.
  # See <https://redis.io/commands/hdel> for more details.
  # @parameter key [Key]
  # @parameter field [String]
  # @returns [Integer] number of deleted fields
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:101
  def hdel(key, *fields); end

  # Determine if a hash field exists. O(1).
  # See <https://redis.io/commands/hexists> for more details.
  # @parameter key [Key]
  # @parameter field [String]
  # @returns [Boolean]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:110
  def hexists(key, field); end

  # Get the value of a hash field. O(1).
  # See <https://redis.io/commands/hget> for more details.
  # @parameter key [Key]
  # @parameter field [String]
  # @returns [String, Null]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:67
  def hget(key, field); end

  # Get all the fields and values in a hash. O(N) where N is the size of the hash.
  # See <https://redis.io/commands/hgetall> for more details.
  # @parameter key [Key]
  # @returns [Hash | Nil]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:154
  def hgetall(key); end

  # Increment the integer value of a hash field by the given number. O(1).
  # See <https://redis.io/commands/hincrby> for more details.
  # @parameter key [Key]
  # @parameter field [String]
  # @parameter increment [Integer]
  # @returns [Integer] field value after increment
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:120
  def hincrby(key, field, increment); end

  # Increment the float value of a hash field by the given amount. O(1).
  # See <https://redis.io/commands/hincrbyfloat> for more details.
  # @parameter key [Key]
  # @parameter field [String]
  # @parameter increment [Double]
  # @returns [Float] field value after increment
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:130
  def hincrbyfloat(key, field, increment); end

  # Get all the fields in a hash. O(N) where N is the size of the hash.
  # See <https://redis.io/commands/hkeys> for more details.
  # @parameter key [Key]
  # @returns [Array]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:138
  def hkeys(key); end

  # Get the number of fields in a hash. O(1).
  # See <https://redis.io/commands/hlen> for more details.
  # @parameter key [Key]
  # @returns [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:17
  def hlen(key); end

  # Get the values of all the given hash fields. O(N) where N is the number of fields being requested.
  # See <https://redis.io/commands/hmget> for more details.
  # @parameter key [Key]
  # @parameter fields [Array(String)] array of fields
  # @returns [Array]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:76
  def hmget(key, *fields); end

  # Set multiple hash fields to multiple values. O(N) where N is the number of fields being set.
  # See <https://redis.io/commands/hmset> for more details.
  # @parameter key [Key]
  # @returns [String] default: "OK"
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:43
  def hmset(key, *attrs); end

  # Iterates fields of Hash types and their associated values. O(1) for every call. O(N) for a complete iteration, including enough command calls for the cursor to return back to 0. N is the number of elements inside the collection.
  # See <https://redis.io/commands/hscan/> for more details.
  # @parameter cursor [Cursor]
  # @returns [Hash]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:164
  def hscan(key, cursor = T.unsafe(nil), match: T.unsafe(nil), count: T.unsafe(nil)); end

  # Iterate over each field and the value of the hash, using HSCAN.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:179
  def hscan_each(key, cursor = T.unsafe(nil), match: T.unsafe(nil), count: T.unsafe(nil), &block); end

  # Set the string value of a hash field. O(1) for each field/value pair added, so O(N) to add N field/value pairs when the command is called with multiple field/value pairs.
  # See <https://redis.io/commands/hset> for more details.
  # @parameter key [Key]
  # @returns [Integer] if new field added returns "1" otherwise "0"
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:25
  def hset(key, field, value); end

  # Set the value of a hash field, only if the field does not exist. O(1).
  # See <https://redis.io/commands/hsetnx> for more details.
  # @parameter key [Key]
  # @parameter field [String]
  # @parameter value [String]
  # @returns [Boolean] "true" if new field added, "false" otherwise
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:35
  def hsetnx(key, field, value); end

  # Get all the values in a hash. O(N) where N is the size of the hash.
  # See <https://redis.io/commands/hvals> for more details.
  # @parameter key [Key]
  # @returns [Array]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:146
  def hvals(key); end

  # Get the values of all the given hash fields and return as array
  #
  # @example
  #   redis.mapped_hmget("hash", "f1", "f2")
  #     # => { "f1" => "v1", "f2" => "v2" }
  #
  # @parameter key [Key]
  # @parameter fields [Array(String)] array of fields
  # @returns [Hash] a hash mapping the specified fields to their values
  #
  # See <#hmget> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:91
  def mapped_hmget(key, *fields); end

  # Set multiple hash fields to multiple values, by providing a hash
  #
  # @example
  #   redis.mapped_hmset("hash", { "f1" => "v1", "f2" => "v2" })
  #     # => "OK"
  #
  # @parameter key [Key]
  # @parameter hash [Hash] a non-empty hash with fields mapping to values
  # @returns [String] default: "OK"
  #
  # See <#hmset> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/hashes.rb:58
  def mapped_hmset(key, hash); end
end

# Methods for managing Redis lists.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:11
module Protocol::Redis::Methods::Lists
  # Remove and get the first element in a list, or block until one is available. O(1).
  # See <https://redis.io/commands/blpop> for more details.
  # @parameter key [Key]
  # @parameter timeout [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:16
  def blpop(*keys, timeout: T.unsafe(nil)); end

  # Remove and get the last element in a list, or block until one is available. O(1).
  # See <https://redis.io/commands/brpop> for more details.
  # @parameter key [Key]
  # @parameter timeout [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:24
  def brpop(*keys, timeout: T.unsafe(nil)); end

  # Pop an element from a list, push it to another list and return it; or block until one is available. O(1).
  # See <https://redis.io/commands/brpoplpush> for more details.
  # @parameter source [Key]
  # @parameter destination [Key]
  # @parameter timeout [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:33
  def brpoplpush(source, destination, timeout); end

  # Get an element from a list by its index. O(N) where N is the number of elements to traverse to get to the element at index. This makes asking for the first or the last element of the list O(1).
  # See <https://redis.io/commands/lindex> for more details.
  # @parameter key [Key]
  # @parameter index [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:41
  def lindex(key, index); end

  # Insert an element before or after another element in a list. O(N) where N is the number of elements to traverse before seeing the value pivot. This means that inserting somewhere on the left end on the list (head) can be considered O(1) and inserting somewhere on the right end (tail) is O(N).
  # See <https://redis.io/commands/linsert> for more details.
  # @parameter key [Key]
  # @parameter where [Enum]
  # @parameter pivot [String]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:51
  def linsert(key, position = T.unsafe(nil), index, value); end

  # Get the length of a list. O(1).
  # See <https://redis.io/commands/llen> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:64
  def llen(key); end

  # Remove and get the first element in a list. O(1).
  # See <https://redis.io/commands/lpop> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:71
  def lpop(key); end

  # Prepend one or multiple elements to a list. O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
  # See <https://redis.io/commands/lpush> for more details.
  # @parameter key [Key]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:79
  def lpush(key, value, *values); end

  # Prepend an element to a list, only if the list exists. O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
  # See <https://redis.io/commands/lpushx> for more details.
  # @parameter key [Key]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:94
  def lpushx(key, value); end

  # Get a range of elements from a list. O(S+N) where S is the distance of start offset from HEAD for small lists, from nearest end (HEAD or TAIL) for large lists; and N is the number of elements in the specified range.
  # See <https://redis.io/commands/lrange> for more details.
  # @parameter key [Key]
  # @parameter start [Integer]
  # @parameter stop [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:103
  def lrange(key, start, stop); end

  # Remove elements from a list. O(N+M) where N is the length of the list and M is the number of elements removed.
  # See <https://redis.io/commands/lrem> for more details.
  # @parameter key [Key]
  # @parameter count [Integer]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:112
  def lrem(key, count, value); end

  # Set the value of an element in a list by its index. O(N) where N is the length of the list. Setting either the first or the last element of the list is O(1).
  # See <https://redis.io/commands/lset> for more details.
  # @parameter key [Key]
  # @parameter index [Integer]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:121
  def lset(key, index, values); end

  # Trim a list to the specified range. O(N) where N is the number of elements to be removed by the operation.
  # See <https://redis.io/commands/ltrim> for more details.
  # @parameter key [Key]
  # @parameter start [Integer]
  # @parameter stop [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:130
  def ltrim(key, start, stop); end

  # Remove and get the last element in a list. O(1).
  # See <https://redis.io/commands/rpop> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:137
  def rpop(key); end

  # Remove the last element in a list, prepend it to another list and return it. O(1).
  # See <https://redis.io/commands/rpoplpush> for more details.
  # @parameter source [Key]
  # @parameter destination [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:145
  def rpoplpush(source, destination = T.unsafe(nil)); end

  # Append one or multiple elements to a list. O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
  # See <https://redis.io/commands/rpush> for more details.
  # @parameter key [Key]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:155
  def rpush(key, value, *values); end

  # Append an element to a list, only if the list exists. O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
  # See <https://redis.io/commands/rpushx> for more details.
  # @parameter key [Key]
  # @parameter element [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/lists.rb:170
  def rpushx(key, value); end
end

# Methods for managing Redis Pub/Sub.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/pubsub.rb:10
module Protocol::Redis::Methods::Pubsub
  # Post a message to a channel.
  # See <https://redis.io/commands/publish> for more details.
  # @parameter channel [String]
  # @parameter message [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/pubsub.rb:15
  def publish(channel, message); end

  # Post a message to a shard channel.
  # See <https://redis.io/commands/spublish> for more details.
  # @parameter channel [String]
  # @parameter message [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/pubsub.rb:23
  def spublish(channel, message); end
end

# Methods for managing Redis scripting.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/scripting.rb:11
module Protocol::Redis::Methods::Scripting
  # Execute a Lua script server side.
  # @parameter script [String] The Lua script to execute.
  # @parameter key_count [Integer] Number of keys that follow.
  # @parameter keys_and_args [Array] Keys followed by arguments to the script.
  # @returns [Object] The result of the script execution.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/scripting.rb:17
  def eval(script, key_count = T.unsafe(nil), *keys_and_args); end

  # Execute a cached Lua script by SHA1 digest.
  # @parameter sha1 [String] The SHA1 digest of the script to execute.
  # @parameter key_count [Integer] Number of keys that follow.
  # @parameter keys_and_args [Array] Keys followed by arguments to the script.
  # @returns [Object] The result of the script execution.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/scripting.rb:26
  def evalsha(sha1, key_count = T.unsafe(nil), *keys_and_args); end

  # Execute script management commands.
  # @parameter subcommand [String|Symbol] The script subcommand (debug, exists, flush, load, kill).
  # @parameter arguments [Array] Additional arguments for the subcommand.
  # @returns [Object] The result of the script command.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/scripting.rb:34
  def script(subcommand, *arguments); end
end

# Methods for managing Redis servers.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/server.rb:11
module Protocol::Redis::Methods::Server
  # Get the client information for the current connection.
  # See <https://redis.io/commands/client-info> for more details.
  # @returns [Hash] A hash containing client metadata.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/server.rb:32
  def client_info; end

  # Remove all keys from the current database.
  # See <https://redis.io/commands/flushdb> for more details.
  # @parameter async [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/server.rb:51
  def flushdb!; end

  # Get information and statistics about the server.
  # See <https://redis.io/commands/info> for more details.
  # @parameter section [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/server.rb:15
  def info; end
end

# Methods for managing Redis sets.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:10
module Protocol::Redis::Methods::Sets
  # Add one or more members to a set. O(1) for each element added, so O(N) to add N elements when the command is called with multiple arguments.
  # See <https://redis.io/commands/sadd> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:15
  def sadd(*arguments); end

  # Get the number of members in a set. O(1).
  # See <https://redis.io/commands/scard> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:22
  def scard(*arguments); end

  # Subtract multiple sets. O(N) where N is the total number of elements in all given sets.
  # See <https://redis.io/commands/sdiff> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:29
  def sdiff(*arguments); end

  # Subtract multiple sets and store the resulting set in a key. O(N) where N is the total number of elements in all given sets.
  # See <https://redis.io/commands/sdiffstore> for more details.
  # @parameter destination [Key]
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:37
  def sdiffstore(*arguments); end

  # Intersect multiple sets. O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
  # See <https://redis.io/commands/sinter> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:44
  def sinter(*arguments); end

  # Intersect multiple sets and store the resulting set in a key. O(N*M) worst case where N is the cardinality of the smallest set and M is the number of sets.
  # See <https://redis.io/commands/sinterstore> for more details.
  # @parameter destination [Key]
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:52
  def sinterstore(*arguments); end

  # Determine if a given value is a member of a set. O(1).
  # See <https://redis.io/commands/sismember> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:60
  def sismember(*arguments); end

  # Get all the members in a set. O(N) where N is the set cardinality.
  # See <https://redis.io/commands/smembers> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:67
  def smembers(*arguments); end

  # Move a member from one set to another. O(1).
  # See <https://redis.io/commands/smove> for more details.
  # @parameter source [Key]
  # @parameter destination [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:76
  def smove(*arguments); end

  # Remove and return one or multiple random members from a set. O(1).
  # See <https://redis.io/commands/spop> for more details.
  # @parameter key [Key]
  # @parameter count [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:84
  def spop(*arguments); end

  # Get one or multiple random members from a set. Without the count argument O(1), otherwise O(N) where N is the absolute value of the passed count.
  # See <https://redis.io/commands/srandmember> for more details.
  # @parameter key [Key]
  # @parameter count [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:92
  def srandmember(*arguments); end

  # Remove one or more members from a set. O(N) where N is the number of members to be removed.
  # See <https://redis.io/commands/srem> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:100
  def srem(*arguments); end

  # Incrementally iterate Set elements. O(1) for every call. O(N) for a complete iteration, including enough command calls for the cursor to return back to 0. N is the number of elements inside the collection..
  # See <https://redis.io/commands/sscan> for more details.
  # @parameter key [Key]
  # @parameter cursor [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:123
  def sscan(*arguments); end

  # Add multiple sets. O(N) where N is the total number of elements in all given sets.
  # See <https://redis.io/commands/sunion> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:107
  def sunion(*arguments); end

  # Add multiple sets and store the resulting set in a key. O(N) where N is the total number of elements in all given sets.
  # See <https://redis.io/commands/sunionstore> for more details.
  # @parameter destination [Key]
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sets.rb:115
  def sunionstore(*arguments); end
end

# Methods for managing Redis sorted sets.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:11
module Protocol::Redis::Methods::SortedSets
  # Remove and return the member with the highest score from one or more sorted sets, or block until one is available. O(log(N)) with N being the number of elements in the sorted set.
  # See <https://redis.io/commands/bzpopmax> for more details.
  # @parameter key [Key]
  # @parameter timeout [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:24
  def bzpopmax(*keys, timeout: T.unsafe(nil)); end

  # Remove and return the member with the lowest score from one or more sorted sets, or block until one is available. O(log(N)) with N being the number of elements in the sorted set.
  # See <https://redis.io/commands/bzpopmin> for more details.
  # @parameter key [Key]
  # @parameter timeout [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:16
  def bzpopmin(*keys, timeout: T.unsafe(nil)); end

  # Add one or more members to a sorted set, or update its score if it already exists. O(log(N)) for each item added, where N is the number of elements in the sorted set.
  # See <https://redis.io/commands/zadd> for more details.
  # @parameter key [Key]
  # @parameter score [Double]
  # @parameter member [String]
  # @parameter others [Array] an array of `score`, `member` elements.
  # @parameter update [Boolean, nil] If true, only update elements that already exist (never add elements). If false, don't update existing elements (only add new elements).
  # @parameter change [Boolean] Modify the return value from the number of new elements added,
  #   to the total number of elements changed; changed elements are new elements added
  #   and elements already existing for which the score was updated.
  # @parameter increment [Boolean] When this option is specified ZADD acts like ZINCRBY;
  #   only one score-element pair can be specified in this mode.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:40
  def zadd(key, score, member, *others, update: T.unsafe(nil), change: T.unsafe(nil), increment: T.unsafe(nil)); end

  # Get the number of members in a sorted set. O(1).
  # See <https://redis.io/commands/zcard> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:61
  def zcard(key); end

  # Count the members in a sorted set with scores within the given values. O(log(N)) with N being the number of elements in the sorted set.
  # See <https://redis.io/commands/zcount> for more details.
  # @parameter key [Key]
  # @parameter min [Double]
  # @parameter max [Double]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:70
  def zcount(key, min, max); end

  # Increment the score of a member in a sorted set. O(log(N)) where N is the number of elements in the sorted set.
  # See <https://redis.io/commands/zincrby> for more details.
  # @parameter key [Key]
  # @parameter increment [Integer]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:79
  def zincrby(key, increment, member); end

  # Intersect multiple sorted sets and store the resulting sorted set in a new key. O(N*K)+O(M*log(M)) worst case with N being the smallest input sorted set, K being the number of input sorted sets and M being the number of elements in the resulting sorted set.
  # See <https://redis.io/commands/zinterstore> for more details.
  # @parameter destination [Key]
  # @parameter keys [Array(Key)]
  # @parameter weights [Array(Integer)]
  # @parameter aggregate [Enum] one of sum, min, max.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:89
  def zinterstore(destination, keys, weights = T.unsafe(nil), aggregate: T.unsafe(nil)); end

  # Count the number of members in a sorted set between a given lexicographical range. O(log(N)) with N being the number of elements in the sorted set.
  # See <https://redis.io/commands/zlexcount> for more details.
  # @parameter key [Key]
  # @parameter min [String]
  # @parameter max [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:113
  def zlexcount(key, min, max); end

  # Remove and return members with the highest scores in a sorted set. O(log(N)*M) with N being the number of elements in the sorted set, and M being the number of elements popped.
  # See <https://redis.io/commands/zpopmax> for more details.
  # @parameter key [Key]
  # @parameter count [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:121
  def zpopmax(key, count = T.unsafe(nil)); end

  # Remove and return members with the lowest scores in a sorted set. O(log(N)*M) with N being the number of elements in the sorted set, and M being the number of elements popped.
  # See <https://redis.io/commands/zpopmin> for more details.
  # @parameter key [Key]
  # @parameter count [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:129
  def zpopmin(key, count = T.unsafe(nil)); end

  # Return a range of members in a sorted set, by index. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements returned.
  # See <https://redis.io/commands/zrange> for more details.
  # @parameter key [Key]
  # @parameter start [Integer]
  # @parameter stop [Integer]
  # @parameter with_scores [Boolean] Return the scores of the elements together with the elements.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:139
  def zrange(key, start, stop, with_scores: T.unsafe(nil)); end

  # Return a range of members in a sorted set, by lexicographical range. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements being returned. If M is constant (e.g. always asking for the first 10 elements with LIMIT), you can consider it O(log(N)).
  # See <https://redis.io/commands/zrangebylex> for more details.
  # @parameter key [Key]
  # @parameter min [String]
  # @parameter max [String]
  # @parameter limit [Tuple(offset, count)] Limit the results to the specified `offset` and `count` items.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:153
  def zrangebylex(key, min, max, limit: T.unsafe(nil)); end

  # Return a range of members in a sorted set, by score. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements being returned. If M is constant (e.g. always asking for the first 10 elements with LIMIT), you can consider it O(log(N)).
  # See <https://redis.io/commands/zrangebyscore> for more details.
  # @parameter key [Key]
  # @parameter min [Integer]
  # @parameter max [Integer]
  # @parameter with_scores [Boolean] Return the scores of the elements together with the elements.
  # @parameter limit [Tuple<offset, count>] Limit the results to the specified `offset` and `count` items.
  #
  # @example Retrieve the first 10 members with score `>= 0` and `<= 100`
  # 	redis.zrangebyscore("zset", "0", "100", limit: [0, 10])
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:184
  def zrangebyscore(key, min, max, with_scores: T.unsafe(nil), limit: T.unsafe(nil)); end

  # Determine the index of a member in a sorted set. O(log(N)).
  # See <https://redis.io/commands/zrank> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:197
  def zrank(key, member); end

  # Remove one or more members from a sorted set. O(M*log(N)) with N being the number of elements in the sorted set and M the number of elements to be removed.
  # See <https://redis.io/commands/zrem> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:205
  def zrem(key, member); end

  # Remove all members in a sorted set between the given lexicographical range. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements removed by the operation.
  # See <https://redis.io/commands/zremrangebylex> for more details.
  # @parameter key [Key]
  # @parameter min [String]
  # @parameter max [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:214
  def zremrangebylex(key, min, max); end

  # Remove all members in a sorted set within the given indexes. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements removed by the operation.
  # See <https://redis.io/commands/zremrangebyrank> for more details.
  # @parameter key [Key]
  # @parameter start [Integer]
  # @parameter stop [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:223
  def zremrangebyrank(key, start, stop); end

  # Remove all members in a sorted set within the given scores. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements removed by the operation.
  # See <https://redis.io/commands/zremrangebyscore> for more details.
  # @parameter key [Key]
  # @parameter min [Double]
  # @parameter max [Double]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:232
  def zremrangebyscore(key, min, max); end

  # Return a range of members in a sorted set, by index, with scores ordered from high to low. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements returned.
  # See <https://redis.io/commands/zrevrange> for more details.
  # @parameter key [Key]
  # @parameter start [Integer]
  # @parameter stop [Integer]
  # @parameter withscores [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:242
  def zrevrange(key, min, max, with_scores: T.unsafe(nil)); end

  # Return a range of members in a sorted set, by lexicographical range, ordered from higher to lower strings. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements being returned. If M is constant (e.g. always asking for the first 10 elements with LIMIT), you can consider it O(log(N)).
  # See <https://redis.io/commands/zrevrangebylex> for more details.
  # @parameter key [Key]
  # @parameter max [String]
  # @parameter min [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:166
  def zrevrangebylex(key, min, max, limit: T.unsafe(nil)); end

  # Return a range of members in a sorted set, by score, with scores ordered from high to low. O(log(N)+M) with N being the number of elements in the sorted set and M the number of elements being returned. If M is constant (e.g. always asking for the first 10 elements with LIMIT), you can consider it O(log(N)).
  # See <https://redis.io/commands/zrevrangebyscore> for more details.
  # @parameter key [Key]
  # @parameter max [Double]
  # @parameter min [Double]
  # @parameter withscores [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:256
  def zrevrangebyscore(key, min, max, with_scores: T.unsafe(nil), limit: T.unsafe(nil)); end

  # Determine the index of a member in a sorted set, with scores ordered from high to low. O(log(N)).
  # See <https://redis.io/commands/zrevrank> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:269
  def zrevrank(key, member); end

  # Incrementally iterate sorted sets elements and associated scores. O(1) for every call. O(N) for a complete iteration, including enough command calls for the cursor to return back to 0. N is the number of elements inside the collection..
  # See <https://redis.io/commands/zscan> for more details.
  # @parameter key [Key]
  # @parameter cursor [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:294
  def zscan(key, cursor = T.unsafe(nil), match: T.unsafe(nil), count: T.unsafe(nil)); end

  # Get the score associated with the given member in a sorted set. O(1).
  # See <https://redis.io/commands/zscore> for more details.
  # @parameter key [Key]
  # @parameter member [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:277
  def zscore(key, member); end

  # Add multiple sorted sets and store the resulting sorted set in a new key. O(N)+O(M log(M)) with N being the sum of the sizes of the input sorted sets, and M being the number of elements in the resulting sorted set.
  # See <https://redis.io/commands/zunionstore> for more details.
  # @parameter destination [Key]
  # @parameter numkeys [Integer]
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/sorted_sets.rb:286
  def zunionstore(*arguments); end
end

# Methods for managing Redis streams.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:10
module Protocol::Redis::Methods::Streams
  # Marks a pending message as correctly processed, effectively removing it from the pending entries list of the consumer group. Return value of the command is the number of messages successfully acknowledged, that is, the IDs we were actually able to resolve in the PEL. O(1) for each message ID processed.
  # See <https://redis.io/commands/xack> for more details.
  # @parameter key [Key]
  # @parameter group [String]
  # @parameter ID [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:99
  def xack(*arguments); end

  # Appends a new entry to a stream. O(1).
  # See <https://redis.io/commands/xadd> for more details.
  # @parameter key [Key]
  # @parameter ID [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:22
  def xadd(*arguments); end

  # Changes (or acquires) ownership of a message in a consumer group, as if the message was delivered to the specified consumer. O(log N) with N being the number of messages in the PEL of the consumer group.
  # See <https://redis.io/commands/xclaim> for more details.
  # @parameter key [Key]
  # @parameter group [String]
  # @parameter consumer [String]
  # @parameter min-idle-time [String]
  # @parameter ID [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:110
  def xclaim(*arguments); end

  # Removes the specified entries from the stream. Returns the number of items actually deleted, that may be different from the number of IDs passed in case certain IDs do not exist. O(1) for each single item to delete in the stream, regardless of the stream size.
  # See <https://redis.io/commands/xdel> for more details.
  # @parameter key [Key]
  # @parameter ID [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:40
  def xdel(*arguments); end

  # Create, destroy, and manage consumer groups. O(1) for all the subcommands, with the exception of the DESTROY subcommand which takes an additional O(M) time in order to delete the M entries inside the consumer group pending entries list (PEL).
  # See <https://redis.io/commands/xgroup> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:80
  def xgroup(*arguments); end

  # Get information on streams and consumer groups. O(N) with N being the number of returned items for the subcommands CONSUMERS and GROUPS. The STREAM subcommand is O(log N) with N being the number of items in the stream.
  # See <https://redis.io/commands/xinfo> for more details.
  # @parameter help [Enum]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:14
  def xinfo(*arguments); end

  # Return the number of entires in a stream. O(1).
  # See <https://redis.io/commands/xlen> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:65
  def xlen(*arguments); end

  # Return information and entries from a stream consumer group pending entries list, that are messages fetched but never acknowledged. O(N) with N being the number of elements returned, so asking for a small fixed number of entries per call is O(1). When the command returns just the summary it runs in O(1) time assuming the list of consumers is small, otherwise there is additional O(N) time needed to iterate every consumer.
  # See <https://redis.io/commands/xpending> for more details.
  # @parameter key [Key]
  # @parameter group [String]
  # @parameter consumer [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:119
  def xpending(*arguments); end

  # Return a range of elements in a stream, with IDs matching the specified IDs interval. O(N) with N being the number of elements being returned. If N is constant (e.g. always asking for the first 10 elements with COUNT), you can consider it O(1).
  # See <https://redis.io/commands/xrange> for more details.
  # @parameter key [Key]
  # @parameter start [String]
  # @parameter end [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:49
  def xrange(*arguments); end

  # Return never seen elements in multiple streams, with IDs greater than the ones reported by the caller for each stream. Can block. For each stream mentioned: O(N) with N being the number of elements being returned, it means that XREAD-ing with a fixed COUNT is O(1). Note that when the BLOCK option is used, XADD will pay O(M) time in order to serve the M clients blocked on the stream getting new data.
  # See <https://redis.io/commands/xread> for more details.
  # @parameter streams [Enum]
  # @parameter key [Key]
  # @parameter id [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:74
  def xread(*arguments); end

  # Return new entries from a stream using a consumer group, or access the history of the pending entries for a given consumer. Can block. For each stream mentioned: O(M) with M being the number of elements returned. If M is constant (e.g. always asking for the first 10 elements with COUNT), you can consider it O(1). On the other side when XREADGROUP blocks, XADD will pay the O(N) time in order to serve the N clients blocked on the stream getting new data.
  # See <https://redis.io/commands/xreadgroup> for more details.
  # @parameter noack [Enum]
  # @parameter streams [Enum]
  # @parameter key [Key]
  # @parameter ID [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:90
  def xreadgroup(*arguments); end

  # Return a range of elements in a stream, with IDs matching the specified IDs interval, in reverse order (from greater to smaller IDs) compared to XRANGE. O(N) with N being the number of elements returned. If N is constant (e.g. always asking for the first 10 elements with COUNT), you can consider it O(1).
  # See <https://redis.io/commands/xrevrange> for more details.
  # @parameter key [Key]
  # @parameter end [String]
  # @parameter start [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:58
  def xrevrange(*arguments); end

  # Trims the stream to (approximately if '~' is passed) a certain size. O(N), with N being the number of evicted entries. Constant times are very small however, since entries are organized in macro nodes containing multiple entries that can be released with a single deallocation.
  # See <https://redis.io/commands/xtrim> for more details.
  # @parameter key [Key]
  # @parameter strategy [Enum]
  # @parameter approx [Enum]
  # @parameter count [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/streams.rb:32
  def xtrim(*arguments); end
end

# Methods for managing Redis strings.
#
# pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:10
module Protocol::Redis::Methods::Strings
  # Append a value to a key. O(1). The amortized time complexity is O(1) assuming the appended value is small and the already present value is of any size, since the dynamic string library used by Redis will double the free space available on every reallocation.
  # See <https://redis.io/commands/append> for more details.
  # @parameter key [Key]
  # @parameter value [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:15
  def append(key, value); end

  # Count set bits in a string. O(N).
  # See <https://redis.io/commands/bitcount> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:22
  def bitcount(key, *range); end

  # Decrement the integer value of a key by one. O(1).
  # See <https://redis.io/commands/decr> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:29
  def decr(key); end

  # Decrement the integer value of a key by the given number. O(1).
  # See <https://redis.io/commands/decrby> for more details.
  # @parameter key [Key]
  # @parameter decrement [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:37
  def decrby(key, decrement); end

  # Get the value of a key. O(1).
  # See <https://redis.io/commands/get> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:44
  def get(key); end

  # Returns the bit value at offset in the string value stored at key. O(1).
  # See <https://redis.io/commands/getbit> for more details.
  # @parameter key [Key]
  # @parameter offset [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:52
  def getbit(key, offset); end

  # Get a substring of the string stored at a key. O(N) where N is the length of the returned string. The complexity is ultimately determined by the returned length, but because creating a substring from an existing string is very cheap, it can be considered O(1) for small strings.
  # See <https://redis.io/commands/getrange> for more details.
  # @parameter key [Key]
  # @parameter start [Integer]
  # @parameter end [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:61
  def getrange(key, start_index, end_index); end

  # Set the string value of a key and return its old value. O(1).
  # See <https://redis.io/commands/getset> for more details.
  # @parameter key [Key]
  # @parameter value [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:69
  def getset(key, value); end

  # Increment the integer value of a key by one. O(1).
  # See <https://redis.io/commands/incr> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:76
  def incr(key); end

  # Increment the integer value of a key by the given amount. O(1).
  # See <https://redis.io/commands/incrby> for more details.
  # @parameter key [Key]
  # @parameter increment [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:84
  def incrby(key, increment); end

  # Increment the float value of a key by the given amount. O(1).
  # See <https://redis.io/commands/incrbyfloat> for more details.
  # @parameter key [Key]
  # @parameter increment [Double]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:92
  def incrbyfloat(key, increment); end

  # Get the values of all the given keys. O(N) where N is the number of keys to retrieve.
  # See <https://redis.io/commands/mget> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:99
  def mget(key, *keys); end

  # Set multiple keys to multiple values. O(N) where N is the number of keys to set.
  # See <https://redis.io/commands/mset> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:105
  def mset(pairs); end

  # Set multiple keys to multiple values, only if none of the keys exist. O(N) where N is the number of keys to set.
  # See <https://redis.io/commands/msetnx> for more details.
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:115
  def msetnx(pairs); end

  # Set the value and expiration in milliseconds of a key. O(1).
  # See <https://redis.io/commands/psetex> for more details.
  # @parameter key [Key]
  # @parameter milliseconds [Integer]
  # @parameter value [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:126
  def psetex(key, milliseconds, value); end

  # Set the string value of a key. O(1).
  # See <https://redis.io/commands/set> for more details.
  # @parameter key [Key]
  # @parameter value [String]
  # @parameter expiration [Enum]
  # @parameter update [Boolean, nil] If true, only update elements that already exist (never add elements). If false, don't update existing elements (only add new elements).
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:136
  def set(key, value, update: T.unsafe(nil), seconds: T.unsafe(nil), milliseconds: T.unsafe(nil)); end

  # Sets or clears the bit at offset in the string value stored at key. O(1).
  # See <https://redis.io/commands/setbit> for more details.
  # @parameter key [Key]
  # @parameter offset [Integer]
  # @parameter value [Integer]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:161
  def setbit(key, offset, value); end

  # Set the value and expiration of a key. O(1).
  # See <https://redis.io/commands/setex> for more details.
  # @parameter key [Key]
  # @parameter seconds [Integer]
  # @parameter value [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:170
  def setex(key, seconds, value); end

  # Set the value of a key, only if the key does not exist. O(1).
  # @returns [Boolean] if the key was set.
  # See <https://redis.io/commands/setnx> for more details.
  # @parameter key [Key]
  # @parameter value [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:179
  def setnx(key, value); end

  # Overwrite part of a string at key starting at the specified offset. O(1), not counting the time taken to copy the new string in place. Usually, this string is very small so the amortized complexity is O(1). Otherwise, complexity is O(M) with M being the length of the value argument.
  # See <https://redis.io/commands/setrange> for more details.
  # @parameter key [Key]
  # @parameter offset [Integer]
  # @parameter value [String]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:188
  def setrange(key, offset, value); end

  # Get the length of the value stored in a key. O(1).
  # See <https://redis.io/commands/strlen> for more details.
  # @parameter key [Key]
  #
  # pkg:gem/protocol-redis#lib/protocol/redis/methods/strings.rb:195
  def strlen(key); end
end

# Represents an error response from the Redis server.
#
# pkg:gem/protocol-redis#lib/protocol/redis/error.rb:13
class Protocol::Redis::ServerError < ::Protocol::Redis::Error; end

# Represents an unknown token error in the Redis protocol.
#
# pkg:gem/protocol-redis#lib/protocol/redis/error.rb:17
class Protocol::Redis::UnknownTokenError < ::Protocol::Redis::Error; end

# pkg:gem/protocol-redis#lib/protocol/redis/version.rb:8
Protocol::Redis::VERSION = T.let(T.unsafe(nil), String)
