# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-sequel` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-sequel`.


# pkg:gem/rubocop-sequel#lib/rubocop/sequel.rb:3
module RuboCop; end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/helpers/migration.rb:4
module RuboCop::Cop; end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/helpers/migration.rb:5
module RuboCop::Cop::Sequel; end

# ConcurrentIndex looks for non-concurrent index creation.
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/concurrent_index.rb:7
class RuboCop::Cop::Sequel::ConcurrentIndex < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sequel::Helpers::Migration

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/concurrent_index.rb:13
  def indexes?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/concurrent_index.rb:17
  def on_send(node); end

  private

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/concurrent_index.rb:27
  def offensive?(args); end
end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/concurrent_index.rb:10
RuboCop::Cop::Sequel::ConcurrentIndex::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/concurrent_index.rb:11
RuboCop::Cop::Sequel::ConcurrentIndex::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/helpers/migration.rb:6
module RuboCop::Cop::Sequel::Helpers; end

# Migration contains helper methods for detecting if a node is inside a `Sequel.migration` block
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/helpers/migration.rb:8
module RuboCop::Cop::Sequel::Helpers::Migration
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/helpers/migration.rb:11
  def sequel_migration_block?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/helpers/migration.rb:18
  def within_sequel_migration?(node); end
end

# IrreversibleMigration looks for methods inside a `change` block that cannot be reversed.
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:7
class RuboCop::Cop::Sequel::IrreversibleMigration < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sequel::Helpers::Migration

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:34
  def on_block(node); end

  private

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:60
  def invalid_primary_key_method?(node); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:74
  def part_of_method_call?(node); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:56
  def valid_change_method?(node); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:46
  def validate_node(node); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:66
  def within_create_table_block?(node); end
end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:31
RuboCop::Cop::Sequel::IrreversibleMigration::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:32
RuboCop::Cop::Sequel::IrreversibleMigration::PRIMARY_KEY_MSG = T.let(T.unsafe(nil), String)

# https://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-A+Basic+Migration
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/irreversible_migration.rb:11
RuboCop::Cop::Sequel::IrreversibleMigration::VALID_CHANGE_METHODS = T.let(T.unsafe(nil), Array)

# JSONColumn looks for non-JSONB columns.
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:7
class RuboCop::Cop::Sequel::JSONColumn < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sequel::Helpers::Migration

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:21
  def column_method?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:17
  def column_type?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:13
  def json_or_hstore?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:32
  def on_block(node); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:25
  def on_send(node); end
end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:10
RuboCop::Cop::Sequel::JSONColumn::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/json_column.rb:11
RuboCop::Cop::Sequel::JSONColumn::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# MigrationName looks for migration files named with a default name.
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/migration_name.rb:7
class RuboCop::Cop::Sequel::MigrationName < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/migration_name.rb:12
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/migration_name.rb:24
  def filename_bad?(path); end
end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/migration_name.rb:10
RuboCop::Cop::Sequel::MigrationName::MSG = T.let(T.unsafe(nil), String)

# PartialConstraint looks for missed usage of partial indexes.
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/partial_constraint.rb:7
class RuboCop::Cop::Sequel::PartialConstraint < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sequel::Helpers::Migration

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/partial_constraint.rb:13
  def add_partial_constraint?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/partial_constraint.rb:17
  def on_send(node); end
end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/partial_constraint.rb:10
RuboCop::Cop::Sequel::PartialConstraint::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/partial_constraint.rb:11
RuboCop::Cop::Sequel::PartialConstraint::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# SaveChanges promotes the use of save_changes.
#
# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/save_changes.rb:7
class RuboCop::Cop::Sequel::SaveChanges < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/save_changes.rb:13
  def model_save?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/save_changes.rb:17
  def on_send(node); end
end

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/save_changes.rb:10
RuboCop::Cop::Sequel::SaveChanges::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sequel#lib/rubocop/cop/sequel/save_changes.rb:11
RuboCop::Cop::Sequel::SaveChanges::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# RuboCop Sequel project namespace
#
# pkg:gem/rubocop-sequel#lib/rubocop/sequel.rb:5
module RuboCop::Sequel; end

# pkg:gem/rubocop-sequel#lib/rubocop/sequel.rb:8
RuboCop::Sequel::CONFIG = T.let(T.unsafe(nil), Hash)

# pkg:gem/rubocop-sequel#lib/rubocop/sequel.rb:7
RuboCop::Sequel::CONFIG_DEFAULT = T.let(T.unsafe(nil), Pathname)

# pkg:gem/rubocop-sequel#lib/rubocop/sequel.rb:6
RuboCop::Sequel::PROJECT_ROOT = T.let(T.unsafe(nil), Pathname)

# A plugin that integrates rubocop-sequel with RuboCop's plugin system.
#
# pkg:gem/rubocop-sequel#lib/rubocop/sequel/plugin.rb:8
class RuboCop::Sequel::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-sequel#lib/rubocop/sequel/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-sequel#lib/rubocop/sequel/plugin.rb:22
  def rules(_context); end

  # pkg:gem/rubocop-sequel#lib/rubocop/sequel/plugin.rb:18
  def supported?(context); end
end

# This module holds the RuboCop Sequel version information.
#
# pkg:gem/rubocop-sequel#lib/rubocop/sequel/version.rb:6
module RuboCop::Sequel::Version; end

# pkg:gem/rubocop-sequel#lib/rubocop/sequel/version.rb:7
RuboCop::Sequel::Version::STRING = T.let(T.unsafe(nil), String)
