# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-graphql` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-graphql`.


# pkg:gem/rubocop-graphql#lib/rubocop/graphql/ext/snake_case.rb:3
module RuboCop; end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql.rb:4
module RuboCop::Cop; end

# Cops for the `GraphQL` department. The department's cops are
# registered for lazy loading and their files are loaded on demand.
# This cop checks whether type definitions are class-based or legacy.
#
# @example
#   # good
#
#   class Example < BaseType
#     ....
#   end
#
#   # bad
#
#   Example = GraphQL::ObjectType.define do
#     ....
#     ....
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql.rb:7
module RuboCop::Cop::GraphQL
  extend ::RuboCop::Cop::LazyLoader
end

#  This cop checks if each field has a description.
#
# @example
#   # good
#
#   class BanUser < BaseMutation
#     argument :uuid, ID, required: true, description: "UUID of the user to ban"
#   end
#
#   # bad
#
#   class BanUser < BaseMutation
#     argument :uuid, ID, required: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_description.rb:21
class RuboCop::Cop::GraphQL::ArgumentDescription < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_description.rb:27
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_description.rb:24
RuboCop::Cop::GraphQL::ArgumentDescription::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_description.rb:25
RuboCop::Cop::GraphQL::ArgumentDescription::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop checks whether field names are snake_case.
#
# @example
#   # good
#
#   class BanUser < BaseMutation
#     argument :user_id, ID, required: true
#   end
#
#   # bad
#
#   class BanUser < BaseMutation
#     argument :userId, ID, required: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_name.rb:21
class RuboCop::Cop::GraphQL::ArgumentName < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_name.rb:29
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_name.rb:27
RuboCop::Cop::GraphQL::ArgumentName::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_name.rb:23
RuboCop::Cop::GraphQL::ArgumentName::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop detects duplicate argument definitions
#
# @example
#   # good
#
#   class BanUser < BaseMutation
#     argument :user_id, ID, required: true
#   end
#
#   # bad
#
#   class BanUser < BaseMutation
#     argument :user_id, ID, required: true
#     argument :user_id, ID, required: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:22
class RuboCop::Cop::GraphQL::ArgumentUniqueness < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodeUniqueness

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:97
  def argument_declarations(param0); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:28
  def on_class(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:73
  def argument_name(node); end

  # Find parent field block, if available
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:78
  def field_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:60
  def register_offense(current); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/argument_uniqueness.rb:25
RuboCop::Cop::GraphQL::ArgumentUniqueness::MSG = T.let(T.unsafe(nil), String)

# Detects writes to the `context` object within GraphQL types.
# Writing to `context` mutates shared state across the query execution,
# which can lead to unexpected behavior and makes code harder to reason about.
#
# This cop is disabled by default.
#
# @example
#   # bad
#   class UserType < BaseType
#     field :name, String, null: false
#
#     def name
#       context[:current_user] = object.user
#       object.name
#     end
#   end
#
#   # bad
#   class UserType < BaseType
#     field :name, String, null: false
#
#     def name
#       context.merge!(current_user: object.user)
#       object.name
#     end
#   end
#
#   # good
#   class UserType < BaseType
#     field :name, String, null: false
#
#     def name
#       viewer = context[:current_user]
#       object.name
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/context_write_in_type.rb:43
class RuboCop::Cop::GraphQL::ContextWriteInType < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/context_write_in_type.rb:50
  def context_write?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/context_write_in_type.rb:54
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/context_write_in_type.rb:44
RuboCop::Cop::GraphQL::ContextWriteInType::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/context_write_in_type.rb:47
RuboCop::Cop::GraphQL::ContextWriteInType::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Optional arguments should have a default value in the resolver signature.
#
# When the client omits an argument declared `required: false`, graphql-ruby leaves it
# out of the keyword arguments entirely, so a required keyword raises
# `ArgumentError: missing keyword`. Giving the keyword a default value is what makes the
# argument actually optional at runtime.
#
# Arguments declared with a `default_value:` are always passed, so they are not reported.
# Neither is `required: :nullable`, which still demands the argument be present.
#
# Both class-level arguments (checked against `#resolve` and `#authorized?`) and
# arguments defined inside a field block (checked against that field's resolver method)
# are covered.
#
# @example
#   # bad
#
#   class SomeResolver < Resolvers::Base
#     argument :name, String, required: false
#
#     def resolve(name:); end
#   end
#
#   # good
#
#   class SomeResolver < Resolvers::Base
#     argument :name, String, required: false
#
#     def resolve(name: nil); end
#   end
#
#   # good - a default value means the keyword is always passed
#
#   class SomeResolver < Resolvers::Base
#     argument :name, String, required: false, default_value: "anonymous"
#
#     def resolve(name:); end
#   end
#
#   # bad
#
#   class UserType < BaseObject
#     field :posts, [PostType], null: false do
#       argument :limit, Integer, required: false
#     end
#
#     def posts(limit:); end
#   end
#
#   # good
#
#   class UserType < BaseObject
#     field :posts, [PostType], null: false do
#       argument :limit, Integer, required: false
#     end
#
#     def posts(limit: 10); end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:65
class RuboCop::Cop::GraphQL::DefaultForOptionalArgument < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:176
  def argument_declaration?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:181
  def field_declaration?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:71
  def on_class(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:142
  def block_arguments(block_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:84
  def check_class_arguments(class_node, defs); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:93
  def check_field_arguments(class_node, defs); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:105
  def check_signature(def_node, keywords); end

  # Class-level `argument` calls: the walk stops at blocks, so field-block arguments
  # (handled separately, against a different method) are not picked up here.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:136
  def class_arguments(class_node); end

  # `def`s owned by this class, keyed by name. A nested class gets its own `on_class`.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:128
  def definitions_in(class_node); end

  # Collects nodes of `type` without descending into a nested class or module body.
  # With `stop_at_block`, a block contributes only the call that opens it, so a nested
  # `field ... do ... end` keeps its own arguments out of the enclosing scope.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:158
  def each_in_scope(node, type, stop_at_block: T.unsafe(nil), found: T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:149
  def field_blocks(class_node); end

  # Keywords of arguments that graphql-ruby may leave out of the resolver call.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:120
  def optional_keywords(argument_nodes); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:66
RuboCop::Cop::GraphQL::DefaultForOptionalArgument::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/default_for_optional_argument.rb:69
RuboCop::Cop::GraphQL::DefaultForOptionalArgument::RESOLVER_METHODS = T.let(T.unsafe(nil), Array)

# Flags field and argument types the project has decided not to expose, with a message
# explaining what to use instead.
#
# Every schema accumulates types that are still resolvable but shouldn't be reached for
# in new code: a scalar kept alive only for backwards compatibility, a type that predates
# a better one, or a builtin whose semantics don't fit the domain -- `Float` for money,
# say, where the serialization loses precision. The convention is usually documented and
# then re-litigated in review; this makes it fail the build instead.
#
# Nothing is disallowed by default: the cop is inert until `Types` is configured.
#
# A configured name matches the written constant exactly, or as a trailing segment of it,
# so `Float` covers `Float`, `Types::Float` and `GraphQL::Types::Float`. Configure
# `GraphQL::Types::Float` instead to match only the fully qualified form.
#
# List types are unwrapped, so `[Float]` and `[Float, null: true]` are flagged too, and
# both the positional type and the `type:` keyword are checked.
#
# @example Types: {'Float' => 'Use Types::Decimal, which serializes as a string.'}
#   # bad
#   field :amount, Float, null: false
#   argument :amount, Float, required: true
#   field :amounts, [Float], null: false
#   field :amount, type: Float, null: false
#
#   # good
#   field :amount, Types::Decimal, null: false
#   argument :amount, Types::Decimal, required: true
#
# @example Types: {'Types::LegacyDate' => 'Use GraphQL::Types::ISO8601Date.'}
#   # bad
#   field :starts_on, Types::LegacyDate, null: false
#
#   # good
#   field :starts_on, GraphQL::Types::ISO8601Date, null: false
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:42
class RuboCop::Cop::GraphQL::DisallowedTypes < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:48
  def on_send(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:103
  def type_declaration?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:108
  def type_kwarg(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:76
  def disallowed_name_for(const_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:62
  def disallowed_types; end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:91
  def each_const_in(node, &block); end

  # Yields the constants a `field`/`argument` call names as its type: the positional type
  # and the `type:` keyword, each unwrapped through any list nesting.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:86
  def each_type_const(send_node, &block); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:66
  def message_for(configured_name); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:43
RuboCop::Cop::GraphQL::DisallowedTypes::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:44
RuboCop::Cop::GraphQL::DisallowedTypes::MSG_WITH_REASON = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/disallowed_types.rb:46
RuboCop::Cop::GraphQL::DisallowedTypes::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_input_type.rb:6
class RuboCop::Cop::GraphQL::ExtractInputType < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_input_type.rb:29
  def on_class(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_input_type.rb:27
RuboCop::Cop::GraphQL::ExtractInputType::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:6
class RuboCop::Cop::GraphQL::ExtractType < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:38
  def on_class(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:51
  def check_fields_prefixes(body); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:69
  def fractured(body); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:93
  def ignored_prefix?(word); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:89
  def message(prefix, field_names); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/extract_type.rb:48
RuboCop::Cop::GraphQL::ExtractType::MSG = T.let(T.unsafe(nil), String)

# Checks consistency of field definitions
#
# EnforcedStyle supports two modes:
#
# `group_definitions` : all field definitions should be grouped together.
#
# `define_resolver_after_definition` : if resolver method exists it should
# be defined right after the field definition.
#
# @example EnforcedStyle: group_definitions (default)
#   # good
#
#   class UserType < BaseType
#     field :first_name, String, null: true
#     field :last_name, String, null: true
#
#     def first_name
#       object.contact_data.first_name
#     end
#
#     def last_name
#       object.contact_data.last_name
#     end
#   end
#
# @example EnforcedStyle: define_resolver_after_definition
#   # good
#
#   class UserType < BaseType
#     field :first_name, String, null: true
#
#     def first_name
#       object.contact_data.first_name
#     end
#
#     field :last_name, String, null: true
#
#     def last_name
#       object.contact_data.last_name
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:47
class RuboCop::Cop::GraphQL::FieldDefinitions < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  include ::RuboCop::Cop::CommentsHelp
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::Sorbet
  include ::RuboCop::GraphQL::Heredoc
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:59
  def field_kwargs(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:76
  def on_class(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:86
  def on_module(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:68
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:100
  def check_grouped_field_declarations(body); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:129
  def check_resolver_is_defined_after_definition(field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:151
  def field_has_no_resolver_method(field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:159
  def field_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:187
  def fields_with_same_resolver(field, resolver); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:114
  def group_field_declarations(corrector, node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:252
  def indent(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:215
  def insert_new_resolver(corrector, field_definition, resolver_definition); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:155
  def multiple_definitions(field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:163
  def offense_message(single_field_using_resolver); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:202
  def place_resolver_after_field_definition(corrector, node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:225
  def remove_old_resolver(corrector, resolver_definition); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:167
  def resolver_defined_after_definition?(field, method_definition); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:243
  def signature_to_insert(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:98
RuboCop::Cop::GraphQL::FieldDefinitions::GROUP_DEFS_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:125
RuboCop::Cop::GraphQL::FieldDefinitions::RESOLVER_AFTER_FIELD_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:126
RuboCop::Cop::GraphQL::FieldDefinitions::RESOLVER_AFTER_LAST_FIELD_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_definitions.rb:56
RuboCop::Cop::GraphQL::FieldDefinitions::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop checks if each field has a description.
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :name, String, "Name of the user", null: true
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :name, String, null: true
#   end
#
# Fields built from a resolver, mutation or subscription class are not
# flagged: graphql-ruby takes their description from that class.
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :posts, resolver: PostsResolver
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_description.rb:31
class RuboCop::Cop::GraphQL::FieldDescription < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_description.rb:37
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_description.rb:34
RuboCop::Cop::GraphQL::FieldDescription::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_description.rb:35
RuboCop::Cop::GraphQL::FieldDescription::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop prevents defining unnecessary resolver methods in cases
#  when :hash_key option can be used
#
# @example
#   # good
#
#   class Types::UserType < Types::BaseObject
#     field :phone, String, null: true, hash_key: :home_phone
#   end
#
#   # bad
#
#   class Types::UserType < Types::BaseObject
#     field :phone, String, null: true
#
#     def phone
#       object[:home_phone]
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:26
class RuboCop::Cop::GraphQL::FieldHashKey < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:32
  def hash_key_to_use(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:46
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:72
  def autocorrect(corrector, node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:64
  def conflict?(suggested_hash_key_name); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:68
  def message(hash_key); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:88
  def resolver_method_definition_for(field); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:43
RuboCop::Cop::GraphQL::FieldHashKey::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_hash_key.rb:44
RuboCop::Cop::GraphQL::FieldHashKey::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop prevents defining unnecessary resolver methods in cases
#  when :method option can be used
#
# @example
#   # good
#
#   class Types::UserType < Types::BaseObject
#     field :phone, String, null: true, method: :home_phone
#   end
#
#   # bad
#
#   class Types::UserType < Types::BaseObject
#     field :phone, String, null: true
#
#     def phone
#       object.home_phone
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:26
class RuboCop::Cop::GraphQL::FieldMethod < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:32
  def method_to_use(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:45
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:68
  def autocorrect(corrector, node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:64
  def message(method_name); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:86
  def method_kwarg_set?(field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:81
  def suggest_method_name_for(field); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:42
RuboCop::Cop::GraphQL::FieldMethod::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_method.rb:43
RuboCop::Cop::GraphQL::FieldMethod::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop checks whether field names are snake_case.
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :first_name, String, null: true
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :firstName, String, null: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_name.rb:25
class RuboCop::Cop::GraphQL::FieldName < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_name.rb:34
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_name.rb:47
  def rename_field_name(corrector, field, node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_name.rb:31
RuboCop::Cop::GraphQL::FieldName::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_name.rb:32
RuboCop::Cop::GraphQL::FieldName::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Detects duplicate field definitions within
# the same type
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :name, String, null: true
#     field :phone, String, null: true do
#       argument :something, String, required: false
#     end
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :name, String, null: true
#     field :phone, String, null: true
#     field :phone, String, null: true do
#       argument :something, String, required: false
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:29
class RuboCop::Cop::GraphQL::FieldUniqueness < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodeUniqueness

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:72
  def false_value?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:77
  def field_declarations(param0); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:35
  def on_class(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:65
  def field_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:56
  def register_offense(current); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/field_uniqueness.rb:32
RuboCop::Cop::GraphQL::FieldUniqueness::MSG = T.let(T.unsafe(nil), String)

# Checks consistency of graphql_name usage
#
# EnforcedStyle supports two modes:
#
# `only_override` : types and mutations should have graphql_name configured only if it's
#  different from the default name
#
# `required` : all types and mutations should have graphql_name configured
#
# @example EnforcedStyle: only_override (default)
#   # good
#
#   class UserType < BaseType
#     graphql_name 'Viewer'
#   end
#
#   # bad
#
#   class UserType < BaseType
#     graphql_name 'User'
#   end
#
# @example EnforcedStyle: required
#   # good
#
#   class UserType < BaseType
#     graphql_name 'User'
#   end
#
#   # bad
#
#   class UserType < BaseType
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/graphql_name.rb:40
class RuboCop::Cop::GraphQL::GraphqlName < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::ConfigurableEnforcedStyle

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/graphql_name.rb:49
  def class_name(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/graphql_name.rb:44
  def graphql_name(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/graphql_name.rb:56
  def on_class(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/graphql_name.rb:53
RuboCop::Cop::GraphQL::GraphqlName::MISSING_NAME = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/graphql_name.rb:54
RuboCop::Cop::GraphQL::GraphqlName::UNNEEDED_OVERRIDE = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/legacy_dsl.rb:22
class RuboCop::Cop::GraphQL::LegacyDsl < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/legacy_dsl.rb:24
  def legacy_dsl?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/legacy_dsl.rb:37
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/legacy_dsl.rb:33
RuboCop::Cop::GraphQL::LegacyDsl::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/legacy_dsl.rb:35
RuboCop::Cop::GraphQL::LegacyDsl::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Detects missing max_complexity configuration in schema files
#
# @example
#   # good
#
#   class AppSchema < BaseSchema
#     max_complexity 42
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_complexity_schema.rb:15
class RuboCop::Cop::GraphQL::MaxComplexitySchema < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_complexity_schema.rb:17
  def max_complexity(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_complexity_schema.rb:23
  def on_class(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_complexity_schema.rb:21
RuboCop::Cop::GraphQL::MaxComplexitySchema::MSG = T.let(T.unsafe(nil), String)

# Detects missing max_depth configuration in schema files
#
# @example
#   # good
#
#   class AppSchema < BaseSchema
#     max_depth 42
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_depth_schema.rb:15
class RuboCop::Cop::GraphQL::MaxDepthSchema < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_depth_schema.rb:17
  def max_depth(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_depth_schema.rb:23
  def on_class(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/max_depth_schema.rb:21
RuboCop::Cop::GraphQL::MaxDepthSchema::MSG = T.let(T.unsafe(nil), String)

#  This cop detects method definitions that are never called because
#  the field's effective `resolver_method` points somewhere else.
#
#  graphql-ruby only ever calls a single method on the type instance:
#  the field's `resolver_method` (which is the resolver class's own
#  method when `resolver:` is set, the explicit `resolver_method:`
#  value when given, or the field name otherwise). Any other
#  same-named method left on the type is unreachable:
#
#  - When `resolver:` is set, the resolver class handles resolution
#    entirely, so neither the field name, `resolver_method:`, nor
#    `method:` (if also given) is ever dispatched to a method on the type.
#  - When only `resolver_method:` is set, that name is the one
#    actually called -- a leftover method matching the plain field
#    name is never reached.
#
# @example
#   # good
#
#   class Types::PostType < Types::BaseObject
#     field :author, resolver: Resolvers::AuthorResolver
#   end
#
#   class Types::PostType < Types::BaseObject
#     field :author, String, null: true, resolver_method: :fetch_author
#
#     def fetch_author
#       object.author
#     end
#   end
#
#   # bad
#
#   class Types::PostType < Types::BaseObject
#     field :author, resolver: Resolvers::AuthorResolver
#
#     def author
#       object.author
#     end
#   end
#
#   class Types::PostType < Types::BaseObject
#     field :author, String, null: true, resolver_method: :fetch_author
#
#     def author
#       object.author
#     end
#
#     def fetch_author
#       object.author
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:59
class RuboCop::Cop::GraphQL::MethodShadowedByResolverMethod < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:68
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:112
  def method_kwarg_name(field); end

  # The `resolver_method:`-named method is the one actually called; only a
  # leftover method matching the plain field name is dead.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:101
  def register_resolver_method_offense(field); end

  # Neither `resolver_method:` nor `method:` has any effect once `resolver:` is
  # set (graphql-ruby always calls the resolver class's own resolver_method), so
  # a method matching the field's own name, an explicit `resolver_method:`, or
  # an explicit `method:` is equally unreachable.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:86
  def register_resolver_offenses(field); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:64
RuboCop::Cop::GraphQL::MethodShadowedByResolverMethod::RESOLVER_METHOD_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:62
RuboCop::Cop::GraphQL::MethodShadowedByResolverMethod::RESOLVER_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/method_shadowed_by_resolver_method.rb:66
RuboCop::Cop::GraphQL::MethodShadowedByResolverMethod::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Checks whether fields with multiple definitions are grouped together.
# @example
#   # good
#
#   class UserType < BaseType
#     field :first_name, String, null: true
#     field :first_name, Name, null: true
#
#     def first_name
#       object.contact_data.first_name
#     end
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :first_name, String, null: true
#
#     def first_name
#       object.contact_data.first_name
#     end
#     field :first_name, Name, null: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:29
class RuboCop::Cop::GraphQL::MultipleFieldDefinitions < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::Heredoc
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:37
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:63
  def field_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:97
  def field_sibling_index(field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:67
  def group_multiple_definitions(corrector, multiple_definitions); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:89
  def has_ungrouped_definitions?(multiple_definitions); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:76
  def insert_new_field(corrector, first, second); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:59
  def multiple_definitions(field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:82
  def remove_old_field(corrector, second); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:57
RuboCop::Cop::GraphQL::MultipleFieldDefinitions::MULTIPLE_DEFINITIONS_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/multiple_field_definitions.rb:35
RuboCop::Cop::GraphQL::MultipleFieldDefinitions::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Detects types that implement Node interface and not have `.authorized?` check.
# Such types can be fetched by ID and therefore should have type level check to
# avoid accidental information exposure.
#
# If `.authorized?` is defined in a parent class, you can add parent to the "SafeBaseClasses"
# to avoid offenses in children.
#
# This cop also checks the `can_can_action` or `pundit_role` methods that
# can be used as part of the Ruby GraphQL Pro.
#
# @example
#   # good
#
#   class UserType < BaseType
#     implements GraphQL::Types::Relay::Node
#
#     field :uuid, ID, null: false
#
#     def self.authorized?(object, context)
#       super && object.owner == context[:viewer]
#     end
#   end
#
#   # good
#
#   class UserType < BaseType
#     implements GraphQL::Types::Relay::Node
#
#     field :uuid, ID, null: false
#
#     class << self
#       def authorized?(object, context)
#         super && object.owner == context[:viewer]
#       end
#     end
#   end
#
#   # good
#
#   class UserType < BaseType
#     implements GraphQL::Types::Relay::Node
#
#     pundit_role :staff
#
#     field :uuid, ID, null: false
#   end
#
#   # good
#
#   class UserType < BaseType
#     implements GraphQL::Types::Relay::Node
#
#     can_can_action :staff
#
#     field :uuid, ID, null: false
#   end
#
#   # bad
#
#   class UserType < BaseType
#     implements GraphQL::Types::Relay::Node
#
#     field :uuid, ID, null: false
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:71
class RuboCop::Cop::GraphQL::NotAuthorizedNodeType < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:94
  def has_authorized_method?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:84
  def has_can_can_action?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:89
  def has_pundit_role?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:75
  def implements_node_type?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:103
  def on_class(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:98
  def on_module(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:128
  def ignored_class?(klass); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:114
  def implements_authorization?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:118
  def possible_parent_classes(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/not_authorized_node_type.rb:72
RuboCop::Cop::GraphQL::NotAuthorizedNodeType::MSG = T.let(T.unsafe(nil), String)

# A non-null field should not have a resolver whose Sorbet signature returns a nilable
# type. The two disagree: the schema promises a value, the signature admits `nil`, and
# graphql-ruby raises an invalid-null error for every object that resolves to `nil`.
#
# Sorbet cannot catch this, because the field declaration is not part of the signature.
# Only the crashing direction is reported: a nullable field with a non-nilable resolver
# is merely imprecise, not broken.
#
# Codebases without Sorbet signatures never trigger this cop.
#
# @example
#   # bad
#
#   class UserType < BaseObject
#     field :name, String, null: false
#
#     sig { override.returns(T.nilable(String)) }
#     def name
#       object.name
#     end
#   end
#
#   # good - the schema admits what the resolver may return
#
#   class UserType < BaseObject
#     field :name, String, null: true
#
#     sig { override.returns(T.nilable(String)) }
#     def name
#       object.name
#     end
#   end
#
#   # good - the resolver guarantees what the schema promises
#
#   class UserType < BaseObject
#     field :name, String, null: false
#
#     sig { override.returns(String) }
#     def name
#       object.name || "anonymous"
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:50
class RuboCop::Cop::GraphQL::NullabilityMismatch < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::Sorbet

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:131
  def nil_class?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:116
  def non_null_field?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:56
  def on_class(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:70
  def on_module(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:126
  def t_any_types(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:121
  def t_nilable?(param0 = T.unsafe(nil)); end

  private

  # Non-null fields owned by this type, keyed by the method that resolves them. Fields
  # handed off to a `resolver:` class are resolved elsewhere, so they are skipped.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:76
  def collect_non_null_fields(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:91
  def nilable_signature?(def_node); end

  # Only the outermost type counts. `T::Array[T.nilable(String)]` is a non-null list of
  # nullable items, which pairs correctly with a `null: false` field.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:102
  def nilable_type?(node); end

  # True when `node`'s nearest enclosing class or module is `owner`, so that a nested
  # type's fields and methods are not attributed to the one around it.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:111
  def owned_by?(node, owner); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/nullability_mismatch.rb:53
RuboCop::Cop::GraphQL::NullabilityMismatch::MSG = T.let(T.unsafe(nil), String)

#  This cop checks if a type (object, input, interface, scalar, union,
#  mutation, subscription, and resolver) has a description.
#
#  Only classes that actually declare a GraphQL type are checked: those whose
#  superclass resolves to a GraphQL base (`Object`, `InputObject`, `Union`,
#  `Enum`, `Scalar`, or anything ending in `Mutation`, `Subscription` or
#  `Resolver`), plus modules that `include` an `*Interface` base. Plain Ruby
#  classes that happen to live alongside types - error classes, analyzers,
#  validators, loaders, generators - are skipped, so they no longer need to be
#  silenced one by one.
#
#  Two kinds of real type declarations are also skipped, because neither
#  surfaces a description in the schema: abstract `Base*` types that other
#  types inherit from, and (unless `IgnoreRootTypes` is disabled) the root
#  operation types `Query`, `Mutation` and `Subscription`.
#
# @example
#   # good
#
#   class Types::UserType < Types::BaseObject
#     description "Represents application user"
#     # ...
#   end
#
#   # bad
#
#   class Types::UserType < Types::BaseObject
#     # ...
#   end
#
# @example
#   # good - not a GraphQL type, so no description is expected
#
#   class TrackingInfoNotAvailable < StandardError; end
#   class UserLoader < GraphQL::Batch::Loader; end
#
# @example
#   # good - abstract base and root operation types carry no description
#
#   class Types::BaseObject < GraphQL::Schema::Object; end
#   class Types::Query < Types::BaseObject; end
#
# @example AdditionalTypeBases: [] (default)
#   # good - `ApplicationType` is not a recognized GraphQL base, so this
#   # class is not checked
#
#   class Types::UserType < ApplicationType
#   end
#
# @example AdditionalTypeBases: ['ApplicationType']
#   # bad - `ApplicationType` is now treated as a GraphQL base
#
#   class Types::UserType < ApplicationType
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:61
class RuboCop::Cop::GraphQL::ObjectDescription < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::DescriptionMethod

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:95
  def on_class(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:103
  def on_module(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:120
  def abstract_base?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:212
  def additional_type_bases; end

  # A method call with no explicit receiver (e.g. `description "..."`,
  # `include Foo`) - the shape of a GraphQL type DSL declaration.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:154
  def bare_call?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:201
  def body_nodes(node); end

  # Single pass over the class body: a `description` satisfies the cop, and a
  # `graphql_name "Query"` marks a root operation type declared under some
  # other class name, which is exempt like a class named `Query` itself.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:185
  def described_or_root_named?(node); end

  # Abstract bases and the root operation types are real GraphQL declarations,
  # but neither surfaces a description in the schema.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:114
  def exempt_type?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:136
  def graphql_base?(const_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:145
  def graphql_namespace?(const_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:128
  def graphql_type_class?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:208
  def ignore_root_types?; end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:172
  def interface_include?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:191
  def root_graphql_name?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:124
  def type_name(node); end

  # Single pass over the module body: an interface module both `include`s an
  # `*Interface` base and (when compliant) declares a `description`.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:160
  def undescribed_interface_module?(node); end
end

# `Base`, or `Base` followed by another word - the naming convention for the
# abstract types that other types inherit from (`BaseObject`, `BaseInterface`).
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:89
RuboCop::Cop::GraphQL::ObjectDescription::ABSTRACT_BASE_NAME = T.let(T.unsafe(nil), Regexp)

# Base class names that mark a GraphQL type when they match exactly, or with
# a `Base` prefix (`GraphQL::Schema::Object`, `Types::BaseObject`).
# Ambiguous words are deliberately not matched as suffixes, so a plain Ruby
# `ValueObject` base is not mistaken for a GraphQL one. `Interface` is absent
# on purpose: graphql-ruby interfaces are modules, so a *class* inheriting an
# `*::Interface` constant is always some other abstract base.
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:72
RuboCop::Cop::GraphQL::ObjectDescription::EXACT_BASES = T.let(T.unsafe(nil), Array)

# A base named exactly `Base` (`Resolvers::Base`) is only a GraphQL base when
# it sits in a namespace that says so.
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:80
RuboCop::Cop::GraphQL::ObjectDescription::GRAPHQL_NAMESPACES = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:64
RuboCop::Cop::GraphQL::ObjectDescription::MSG = T.let(T.unsafe(nil), String)

# GraphQL reserves these names for the root operation types.
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:85
RuboCop::Cop::GraphQL::ObjectDescription::ROOT_TYPE_NAMES = T.let(T.unsafe(nil), Array)

# Sorbet's `T` namespace is reserved, and `T::Enum` / `T::Struct` collide with
# the base names above.
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:93
RuboCop::Cop::GraphQL::ObjectDescription::SORBET_NAMESPACE = T.let(T.unsafe(nil), Symbol)

# These read unambiguously as GraphQL even inside a longer name, so they are
# matched as suffixes (`RelayClassicMutation`, `Base::PermissionedMutation`).
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/object_description.rb:76
RuboCop::Cop::GraphQL::ObjectDescription::SUFFIX_BASES = T.let(T.unsafe(nil), Array)

# Arguments should be alphabetically sorted within groups.
#
# @example
#   # good
#
#   class UpdateProfile < BaseMutation
#     argument :email, String, required: false
#     argument :name, String, required: false
#   end
#
#   # good
#
#   class UpdateProfile < BaseMutation
#     argument :uuid, ID, required: true
#
#     argument :email, String, required: false
#     argument :name, String, required: false
#   end
#
#   # good
#
#   class UserType < BaseType
#     field :posts, PostType do
#       argument :created_after, ISO8601DateTime, required: false
#       argument :created_before, ISO8601DateTime, required: false
#     end
#   end
#
#   # bad
#
#   class UpdateProfile < BaseMutation
#     argument :uuid, ID, required: true
#     argument :name, String, required: false
#     argument :email, String, required: false
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :posts, PostType do
#       argument :created_before, ISO8601DateTime, required: false
#       argument :created_after, ISO8601DateTime, required: false
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:51
class RuboCop::Cop::GraphQL::OrderedArguments < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::SwapRange
  include ::RuboCop::GraphQL::CompareOrder
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:108
  def argument_declaration(param0); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:60
  def on_class(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:81
  def argument_declaration_with_block?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:97
  def argument_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:103
  def consecutive_lines(previous, current); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:85
  def register_offense(previous, current); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_arguments.rb:57
RuboCop::Cop::GraphQL::OrderedArguments::MSG = T.let(T.unsafe(nil), String)

# Fields should be alphabetically sorted within groups.
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :name, String, null: true
#     field :phone, String, null: true do
#       argument :something, String, required: false
#     end
#   end
#
#   # good
#
#   class UserType < BaseType
#     field :phone, String, null: true
#
#     field :name, String, null: true
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :phone, String, null: true
#     field :name, String, null: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:33
class RuboCop::Cop::GraphQL::OrderedFields < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::SwapRange
  include ::RuboCop::GraphQL::CompareOrder
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:44
  def field_declarations(param0); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:58
  def on_block(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:52
  def on_class(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:66
  def on_itblock(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:56
  def on_module(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:67
  def on_numblock(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:71
  def check_field_ordering(fields); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:94
  def consecutive_fields(previous, current); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:84
  def direct_child_field?(field_node, class_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:80
  def direct_field_declarations(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:114
  def field_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:102
  def register_offense(previous, current); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/ordered_fields.rb:39
RuboCop::Cop::GraphQL::OrderedFields::MSG = T.let(T.unsafe(nil), String)

# Checks that GraphQL Argument definitions prepare arguments use String or constants
# instead of `prepare: CONST_REF`
# This allows better Sorbet typing.
#
# Preference is given to an input object declaring a `def prepare(...); end` method
#
# @example
#   # bad
#   PREPARE = ->(input, context) { ... }
#
#   argument :input, prepare: PREPARE
#
#   # good
#   def input_prepare(input); ...; end
#
#   argument :input, prepare: :input_prepare
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:25
class RuboCop::Cop::GraphQL::PrepareMethod < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:37
  def graphql_argument_with_prepare_block?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:51
  def on_send(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:42
  def prepare_method_string_name?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:47
  def prepare_method_symbol_name?(param0 = T.unsafe(nil)); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:87
  def autocorrect(corrector, node, original_method_name, new_method_name); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:34
RuboCop::Cop::GraphQL::PrepareMethod::ARGUMENT_METHODS = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:27
RuboCop::Cop::GraphQL::PrepareMethod::GENERAL_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:30
RuboCop::Cop::GraphQL::PrepareMethod::PREFER_STRING_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:32
RuboCop::Cop::GraphQL::PrepareMethod::PREFER_SYMBOL_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:29
RuboCop::Cop::GraphQL::PrepareMethod::STRING_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/prepare_method.rb:31
RuboCop::Cop::GraphQL::PrepareMethod::SYMBOL_MSG = T.let(T.unsafe(nil), String)

# Checks if the length of a resolver method exceeds some maximum value.
# Comment lines can optionally be ignored.
#
# The maximum allowed length is configurable using the Max option.
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:10
class RuboCop::Cop::GraphQL::ResolverMethodLength < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::CodeLength

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:16
  def field_definition(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:20
  def on_def(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:34
  def on_defs(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:38
  def field_is_defined?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:45
  def message(length); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/resolver_method_length.rb:13
RuboCop::Cop::GraphQL::ResolverMethodLength::MSG = T.let(T.unsafe(nil), String)

#  This cop checks if each argument has an unnecessary camelize.
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :name, String, "Name of the user", null: true do
#       argument :filter, String, required: false
#     end
#   end
#
#   # good
#
#   class UserType < BaseType
#     argument :filter, String, required: false
#   end
#
#   # good
#
#   class UserType < BaseType
#     argument :email_filter, String, required: false, camelize: true
#   end
#
#  # bad
#
#   class UserType < BaseType
#     argument :filter, String, required: false, camelize: false
#   end
#
#  # bad
#
#   class UserType < BaseType
#     field :name, String, "Name of the user", null: true do
#       argument :filter, String, required: false, camelize: false
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_argument_camelize.rb:43
class RuboCop::Cop::GraphQL::UnnecessaryArgumentCamelize < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_argument_camelize.rb:49
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_argument_camelize.rb:46
RuboCop::Cop::GraphQL::UnnecessaryArgumentCamelize::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_argument_camelize.rb:47
RuboCop::Cop::GraphQL::UnnecessaryArgumentCamelize::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop prevents defining an unnecessary alias, method, or resolver_method.
#
# @example
#   # good
#
#   field :name, String, "Name of the user", null: true, alias: :real_name
#   field :name, String, "Name of the user", null: true, method: :real_name
#   field :name, String, "Name of the user", null: true, resolver_method: :real_name
#   field :name, String, "Name of the user", null: true, hash_key: :real_name
#
#   # bad
#
#   field :name, "Name of the user" String, null: true, alias: :name
#   field :name, String, "Name of the user", null: true, method: :name
#   field :name, String, "Name of the user", null: true, resolver_method: :name
#   field :name, String, "Name of the user", null: true, hash_key: :name
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_alias.rb:23
class RuboCop::Cop::GraphQL::UnnecessaryFieldAlias < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_alias.rb:30
  def on_send(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_alias.rb:49
  def validate_kwargs(field); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_alias.rb:27
RuboCop::Cop::GraphQL::UnnecessaryFieldAlias::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_alias.rb:28
RuboCop::Cop::GraphQL::UnnecessaryFieldAlias::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

#  This cop checks if each field has an unnecessary camelize.
#
# @example
#   # good
#
#   class UserType < BaseType
#     field :name, String, "Name of the user", null: true
#   end
#
#   # bad
#
#   class UserType < BaseType
#     field :name, "Name of the user", String, null: true, camelize: true
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_camelize.rb:21
class RuboCop::Cop::GraphQL::UnnecessaryFieldCamelize < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_camelize.rb:27
  def on_send(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_camelize.rb:24
RuboCop::Cop::GraphQL::UnnecessaryFieldCamelize::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unnecessary_field_camelize.rb:25
RuboCop::Cop::GraphQL::UnnecessaryFieldCamelize::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# Arguments should either be listed explicitly or **rest should be in the resolve signature
# (and similar methods, such as #authorized?).
#
# @example
#   # good
#
#   class SomeResolver < Resolvers::Base
#     argument :arg1, String, required: true
#     argument :user_id, String, required: true, loads: Types::UserType
#     argument :post_id, String, loads: Types::PostType, as: :article
#     argument :comment_ids, String, loads: Types::CommentType
#
#     def authorized?(arg1:, user:, article:, comments:); end
#     def resolve(arg1:, user:, article:, comments:); end
#   end
#
#   # good
#
#   class SomeResolver < Resolvers::Base
#     argument :arg1, String, required: true
#     argument :user_id, String, required: true, loads: Types::UserType
#     argument :comment_ids, String, loads: Types::CommentType
#
#     def resolve(arg1:, **rest); end
#   end
#
#   # good
#
#   class SomeResolver < Resolvers::Base
#     type SomeType, null: false
#
#     argument :arg1, String, required: true
#     argument :arg2, String, required: true
#
#     def resolve(args); end
#   end
#
#   # bad
#
#   class SomeResolver < Resolvers::Base
#     type SomeType, null: false
#
#     argument :arg1, String, required: true
#     argument :arg2, String, required: true
#
#     def authorized?; end
#     def resolve(arg1:); end
#   end
#
#   # bad
#
#   class SomeResolver < Resolvers::Base
#     type SomeType, null: false
#
#     argument :arg1, String, required: true
#     argument :arg2, String, required: true
#
#     def resolve; end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:66
class RuboCop::Cop::GraphQL::UnusedArgument < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:163
  def argument_declaration?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:71
  def on_class(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:168
  def resolve_method_definition(param0); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:146
  def arg_end(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:158
  def block_or_lambda?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:84
  def find_declared_arg_nodes(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:96
  def find_resolve_method_node(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:104
  def find_unresolved_args(method_node, declared_arg_nodes); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:117
  def ignore_arguments_type?(resolve_method_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:142
  def method_name(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:123
  def register_offense(node, unresolved_args); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:154
  def scope_changing_syntax?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:150
  def scoped_node?(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/unused_argument.rb:69
RuboCop::Cop::GraphQL::UnusedArgument::MSG = T.let(T.unsafe(nil), String)

#  This cop detects `resolver_method:` or `method:` options that have no
#  effect, either because:
#
#  - the same field also sets `resolver:` -- graphql-ruby always calls
#    the resolver class's own resolver_method once `resolver:` is set,
#    silently ignoring both `resolver_method:` and `method:` regardless
#    of whether a method by either name exists; or
#  - a method matching the field's own plain name is also defined on the
#    type -- that method is checked (and wins) before `method:` is ever
#    considered, since `method:` is only consulted as a fallback when no
#    such method exists. This only applies to `method:`: `resolver_method:`
#    redirects which name is checked instead of competing with it, so it
#    can't be shadowed by a same-named `def` the way `method:` can.
#
# @example
#   # good
#
#   class Types::PostType < Types::BaseObject
#     field :author, resolver: Resolvers::AuthorResolver
#   end
#
#   class Types::PostType < Types::BaseObject
#     field :author, String, null: true, method: :ghostwriter
#   end
#
#   # bad
#
#   class Types::PostType < Types::BaseObject
#     field :author, resolver: Resolvers::AuthorResolver, resolver_method: :fetch_author
#   end
#
#   class Types::PostType < Types::BaseObject
#     field :author, resolver: Resolvers::AuthorResolver, method: :ghostwriter
#   end
#
#   class Types::PostType < Types::BaseObject
#     field :author, String, null: true, method: :ghostwriter
#
#     def author
#       object.author
#     end
#   end
#
# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:49
class RuboCop::Cop::GraphQL::UselessMethodOption < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:62
  def method_pair(param0); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:64
  def on_send(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:59
  def resolver_method_pair(param0); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:87
  def register_method_shadowed_by_def_offense(node, field); end

  # pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:78
  def register_resolver_offenses(node, field); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:54
RuboCop::Cop::GraphQL::UselessMethodOption::DEF_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:52
RuboCop::Cop::GraphQL::UselessMethodOption::RESOLVER_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/cop/graphql/useless_method_option.rb:56
RuboCop::Cop::GraphQL::UselessMethodOption::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

# RuboCop GraphQL project namespace.
#
# pkg:gem/rubocop-graphql#lib/rubocop/graphql/ext/snake_case.rb:4
module RuboCop::GraphQL; end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:5
class RuboCop::GraphQL::Argument
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:30
  def initialize(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:19
  def argument_as(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:9
  def argument_description(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:14
  def argument_name(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:24
  def argument_required(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:38
  def as; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:73
  def block; end

  # A configured default is always passed, even when the client omits the argument.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:61
  def default_value?; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:65
  def description; end

  # The keyword this argument is passed as to #resolve and friends. `as:` wins when both
  # are given, matching graphql-ruby's `kwargs[:as] ||= inferred_arg_name`.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:44
  def keyword; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:69
  def kwargs; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:34
  def name; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:28
  def node; end

  # `required: false` is the only value that lets graphql-ruby omit the keyword:
  # `required: :nullable` still demands the argument be present, though it may be null.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:53
  def optional?; end

  private

  # Mirrors graphql-ruby: a `loads:` argument named `foo_id` arrives as `foo:`, and one
  # named `foo_ids` arrives as `foos:`.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument.rb:81
  def inferred_keyword; end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/block.rb:6
class RuboCop::GraphQL::Argument::Block
  include ::RuboCop::GraphQL::DescriptionMethod
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/block.rb:19
  def initialize(argument_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/block.rb:11
  def argument_block(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/block.rb:23
  def description; end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:6
class RuboCop::GraphQL::Argument::Kwargs
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:49
  def initialize(argument_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:10
  def argument_kwargs(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:65
  def as; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:30
  def as_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:57
  def camelize; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:35
  def camelize_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:73
  def default_value; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:45
  def default_value_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:53
  def description; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:20
  def description_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:61
  def loads; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:25
  def loads_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:69
  def required; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/argument/kwargs.rb:40
  def required_kwarg?(param0 = T.unsafe(nil)); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/class.rb:5
class RuboCop::GraphQL::Class
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/class.rb:8
  def initialize(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/class.rb:12
  def nested?; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/class.rb:6
  def node; end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/compare_order.rb:5
module RuboCop::GraphQL::CompareOrder
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/compare_order.rb:6
  def correct_order?(previous, current); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/compare_order.rb:34
  def order_index(field, order); end
end

# Matches a variety of description formats commonly seen in Rails applications
#
#   description 'blah'
#
#   description "blah"
#
#   description <<~EOT
#      blah
#      bloop
#   EOT
#
#   description <<-EOT.squish
#      blah
#      bloop
#   EOT
#
# pkg:gem/rubocop-graphql#lib/rubocop/graphql/description_method.rb:20
module RuboCop::GraphQL::DescriptionMethod
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/description_method.rb:26
  def description_method_call?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/description_method.rb:31
  def description_with_block_arg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/description_method.rb:35
  def find_description_method(nodes); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/description_method.rb:23
RuboCop::GraphQL::DescriptionMethod::DESCRIPTION_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/ext/snake_case.rb:5
module RuboCop::GraphQL::Ext; end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/ext/snake_case.rb:6
module RuboCop::GraphQL::Ext::SnakeCase; end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/ext/snake_case.rb:7
RuboCop::GraphQL::Ext::SnakeCase::SNAKE_CASE = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:5
class RuboCop::GraphQL::Field
  extend ::Forwardable
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:41
  def initialize(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:72
  def block; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:60
  def description; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:35
  def field_description(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:24
  def field_name(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:29
  def field_with_body_name(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:68
  def kwargs; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:45
  def name; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:39
  def node; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:21
  def parent(*args, **_arg1, &block); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:64
  def resolver_method_name; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:76
  def schema_member; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:21
  def sibling_index(*args, **_arg1, &block); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:49
  def underscore_name; end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:82
  def root_node; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:86
  def root_node?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:93
  def root_with_siblings?(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/block.rb:6
class RuboCop::GraphQL::Field::Block
  include ::RuboCop::GraphQL::DescriptionMethod
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/block.rb:19
  def initialize(field_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/block.rb:23
  def description; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/block.rb:11
  def field_block(param0 = T.unsafe(nil)); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:17
RuboCop::GraphQL::Field::CONFLICT_FIELD_NAMES = T.let(T.unsafe(nil), Set)

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:15
RuboCop::GraphQL::Field::GRAPHQL_RUBY_KEYWORDS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:6
class RuboCop::GraphQL::Field::Kwargs
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:64
  def initialize(field_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:90
  def alias; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:40
  def alias_kwarg(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:94
  def camelize; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:60
  def camelize_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:102
  def description; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:50
  def description_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:10
  def field_kwargs(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:98
  def hash_key; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:45
  def hash_key_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:86
  def method; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:35
  def method_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:72
  def mutation; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:25
  def mutation_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:68
  def resolver; end

  # graphql-ruby builds the field's resolver class out of any one of these
  # options, and the field then inherits configuration from that class.
  #
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:82
  def resolver_class; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:20
  def resolver_kwarg?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:106
  def resolver_method_name; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:55
  def resolver_method_option(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:76
  def subscription; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/field/kwargs.rb:30
  def subscription_kwarg?(param0 = T.unsafe(nil)); end
end

# These constants were extracted from graphql-ruby in lib/graphql/schema/member/has_fields.rb
#
# pkg:gem/rubocop-graphql#lib/rubocop/graphql/field.rb:10
RuboCop::GraphQL::Field::RUBY_KEYWORDS = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/heredoc.rb:5
module RuboCop::GraphQL::Heredoc
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/heredoc.rb:6
  def heredoc?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/heredoc.rb:10
  def range_including_heredoc(node); end

  private

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/heredoc.rb:21
  def find_last_heredoc(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_pattern.rb:5
module RuboCop::GraphQL::NodePattern
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_pattern.rb:22
  def argument?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_pattern.rb:26
  def field?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_pattern.rb:9
  def field_definition?(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_pattern.rb:14
  def field_definition_with_body?(param0 = T.unsafe(nil)); end
end

# Shared methods to check duplicated definitions
#
# pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_uniqueness.rb:6
module RuboCop::GraphQL::NodeUniqueness
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/node_uniqueness.rb:7
  def current_class_full_name(node); end
end

# A plugin that integrates rubocop-graphql with RuboCop's plugin system.
#
# pkg:gem/rubocop-graphql#lib/rubocop/graphql/plugin.rb:8
class RuboCop::GraphQL::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/plugin.rb:22
  def rules(_context); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/plugin.rb:18
  def supported?(context); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/schema_member.rb:5
class RuboCop::GraphQL::SchemaMember
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/schema_member.rb:15
  def initialize(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/schema_member.rb:23
  def body; end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/schema_member.rb:9
  def class_contents(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/schema_member.rb:19
  def find_method_definition(method_name); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/schema_member.rb:13
  def node; end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/sorbet.rb:5
module RuboCop::GraphQL::Sorbet
  extend ::RuboCop::AST::NodePattern::Macros

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/sorbet.rb:13
  def has_sorbet_signature?(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/sorbet.rb:9
  def sorbet_signature(param0 = T.unsafe(nil)); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/sorbet.rb:17
  def sorbet_signature_for(node); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/swap_range.rb:5
module RuboCop::GraphQL::SwapRange
  include ::RuboCop::Cop::RangeHelp

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/swap_range.rb:16
  def declaration(node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/swap_range.rb:25
  def final_end_location(start_node); end

  # pkg:gem/rubocop-graphql#lib/rubocop/graphql/swap_range.rb:8
  def swap_range(corrector, current, previous); end
end

# pkg:gem/rubocop-graphql#lib/rubocop/graphql/version.rb:3
RuboCop::GraphQL::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-graphql#lib/refinements/underscore_string.rb:3
module UnderscoreString; end
